### ISSUE TITLE
What value I should use for -o (number of outstanding I/O requests per target)

### ISSUE THREAD

**Issue by tlsalex** [microsoft/diskspd#106]
What value I should use for -o (number of outstanding I/O requests per target) in order to get to know the of performance of my disk ?

I am not quite understand Diskspd, how does it work ? by always keep one IO in the disk queue ,then disk will keep reading or writing (never stop in the duration), then can figure out how many IO it can complete per second , right or not ?

If it is right , so I should always set the value of -o to 1 ? but google the internet ,I found many people use different value , rather than 1 .

Bellow is my test result of my hard drive , it's around 100 IOPS , AvgLat is around 55ms, how can I say it's bad or not ?

BTW , how to get the total amount of random IO generated by system , otherwise how can I know the system generated random IO is too much for my drive 

If a VM system will generate 50 random IO per second , then my drive still can survive with 2 VM , which is 50*2 = 100 IOPS , but with 3 VM ,that is 50x3 > 100 IOPS , my hard drive will die , it it correct ?

![image](https://user-images.githubusercontent.com/36788337/59559480-93948d80-903a-11e9-9823-817e241ca238.png)

**Comment by dl2n** [comment]
-o specifies the number of asynchronous IOs to try to keep in-flight (queue depth) per thread per target. Many modern devices can handle more than one IO at a time in parallel, so -o1 may not get close to saturating them.

Your result is not around 100 IOPS. Its closer to 450, the sum of each thread's results. You should have seen that on a following line.

Average latency was around 35ms, not 55. Don't confuse the standard deviation of the latencies with the average latency, though you should observe that the very high stddev means the latencies were very variable.

If this was a plain HDD, and from the average latency/stddev I'm prepared to suspect that, the reason you got ~450 IOPS was by queueing somewhat deeply (even 4 is deep, if you'd said -t4 o1) to a limited range of the HDD surface (1024MiB = 1GiB). The seek cost on an HDD is reduced if the range is confined to a narrow band (if you like, search the web for "hdd short stroke"). This is not representative of what you would see in normal operation, where your workingset would presumably not be quite so small/confined. If you expand the test to cover more of the HDD (say, 25% of capacity) you may get something more representative, and it may be considerably lower.

**Comment by dl2n** [comment]
Closing old q&a issue.
