### ISSUE TITLE
Memory map fails with Error saying it cannot map the file

### ISSUE THREAD

**Issue by shubhamacheeri** [microsoft/diskspd#119]
-Sm and -Smw option fails saying it cannot map the file?
Am I missing anything?

Output below:
C:\Users\Administrator\Desktop\x86>diskspd.exe -c2G -b4K -F8 -r -o32 -W60 -d60 -Sm D:\test.wim
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
FATAL ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8
ERROR: Could not map view for target 'D:\test.wim'. Error code: 0x8

**Comment by DanPear** [comment]
The error code 0x8 maps to: Not enough memory resources are available to process this command.

If you're using a 64-bit platform then switch to using the 64-bit version of the tool. On a 32-bit platform you'll need to use a smaller file size for memory mapped operations.

**Comment by shubhamacheeri** [comment]
Thanks Dan. But I do not understand why there is not enough memory resources..i am trying to mmap a file which is just a few KB. And even a 100GB files get mapped if I map it using MapViewofFile by own program of mine?
Am I missing something?

**Comment by shubhamacheeri** [comment]
Thanks Dan. But I do not understand why there is not enough memory resources..i am trying to mmap a file which is just a few KB. And even a 100GB files get mapped if I map it using MapViewofFile by own program of mine?
Also when I downloaded the package, I got only one .exe file under x86 directory. I did not see separate 64 bit version/ 32 bit versions?
Thanks
Shubha

**Comment by DanPear** [comment]
You're using the -c option which instructs the tool to create a new file. If you wish to use an existing file then you need to omit the option and just pass in the file name, e.g. diskspd.exe -b4K -F8 -r -o32 -W60 -d60 -Sm D:\test.wim.

If you've downloaded the official release of the tool then you should find the 64-bit version in the amd64 directory. On a 64-bit platform that version will work with your original command line. Please note though that the -c option will replace the existing file.

**Comment by shubhamacheeri** [comment]
Hi Dan,
Nope, even if I omit the -c option, I get the very same error. I will try with 64 bit version. Mine is an intel machine, so I had not tried the amd folder :)
I will try the 64 bit version and let you know.
Thanks
Shubha

**Comment by DanPear** [comment]
Please check the size of D:\test.wim again as it's most probably been modified to 2 GB.

**Comment by shubhamacheeri** [comment]
Yes it is. It is modified to 2GB. But why does it fail to map..Is it because I am using the normal one , not the one under AMD folder?

**Comment by shubhamacheeri** [comment]
HI Dan,yes when I used the exe from AMD folder, it worked well, thanks! It was indeed a s 64bit exe that was required to run welll.

**Comment by shubhamacheeri** [comment]
Hi, One more quick question. Is there a way to run the DiskSpd test for a particular number of IOs instead of time duration?  like can i instrcut it to run until it finishes "x" number of IOs and record the time spent for it? And is there an example to notify another process when it finishes that many IOs?

Thanks
Shubha

**Comment by dl2n** [comment]
Question transferred to #120
