### ISSUE TITLE
DISKSPD uses a couple APIs not in Nano Server 2016

### ISSUE THREAD

**Issue by dl2n** [Microsoft/diskspd#12]
Per http://blogs.technet.com/b/nanoserver/archive/2015/11/16/native-binary-scanning-tool-nanoserverapiscan-exe-for-nano-server.aspx

These two APIs are not present in Nano Server 2016. Removing dependencies on them will allow DISKSPD to work on that platform.

PS X:\nano> .\NanoServerApiScan.exe /BinaryPath:Z:\tmp
-----------------------------------------------------------------------------
=== diskspd.exe ===
=== Z:\tmp\diskspd.exe ===

ERRORS:

  KERNEL32.dll
    SetThreadAffinityMask (Proc not found)
  ole32.dll
    CoInitialize (Proc not found)
      Please use API CoInitializeEx as substitution.

**Comment by rob-scheepens** [comment]
SetThreadAffinityMask is shown as a compatible API on https://msdn.microsoft.com/en-us/library/mt588480(v=vs.85).aspx#api-ms-win-core-processtopology-obsolete-l1-1-0.dll. If this indeed is an error, then what API should be used instead?

**Comment by dl2n** [comment]
This is now handled, will be fixed in next push.

**Comment by dl2n** [comment]
Fixed in 2.0.16b
