### ISSUE TITLE
Sequential Writes and Random Reads

### ISSUE THREAD

**Issue by gmgifpe** [microsoft/diskspd#122]
I'm trying to write a few tests in diskspd to run mix reads and write for either random or sequential.
Is there any possible way to do Sequential Writes and Random Reads mix?

Thanks

**Comment by ale-goncalves** [comment]
Sequential and Random patterns are exclusive of each other. https://github.com/microsoft/diskspd/wiki/Customizing-tests#set-random-or-sequential-access-hints

You can try two diskspd sessions to different test files if you want to test the disk behavior.

**Comment by gmgifpe** [comment]
Thank you for the reply.
But at the same time I want to keep the proportion both for the read and write.
So the test workload like "30% sequential write 70% random read".
Is there any way to reach this target? 

Thanks.

**Comment by dl2n** [comment]
DISKSPD does not support this type of operation. It is possible to get sequential writes and random reads from two <Target> specifications in the XML profile support (-X), but there is no way of driving a specific ratio of IO between them (unless you use rate limiting, i.e. -g). That could be effective for your case though.

**Comment by dl2n** [comment]
Closing old q&a issue.
