### ISSUE TITLE
How to use process-diskspd.ps1 

### ISSUE THREAD

**Issue by rhavinal** [microsoft/diskspd#124]
how to use process-diskspd.ps1 file? Is there an example? 

.\diskspd.exe -b512K -d15 -o8 -t8 -h -r -w0 -L -Z1G -c200M \\10.10.10.72\Ram_Disk2\00.dat > C:\Users\Administrator\Desktop\result.xml

After this step? ".\Process-DiskSpd.ps1 result.xml" gives lot of errors.

**Comment by dl2n** [comment]
The default output is plain text. Use -Rxml to get the result in XML form for process-diskspd.

You are doing a read-only test (-w0). -Z does not apply to that scenario – only if writes are occurring. However, if you were doing writes it is unlikely you need 1GiB of random write buffer source. On the order of 10’s of megabytes is more reasonable, and all that’s needed to defeat inline dedup or constant buffer detection if you have that present.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
