### ISSUE TITLE
Save more data to csv and html files

### ISSUE THREAD

**Issue by Alfarek** [microsoft/diskspd#125]
Hi,

I am using this script for benchmarking storage for sql server purposes. I appreciate your work.
it would help me a lot if you would implement on more thing :)

When I test several servers, disks configurations I would need to save more to csv and html file:
1. Settings - all of them
2. BlockSize from tested disk using fsutil

It is very important when you would like to compare the results to each other.

Best regards 
Tom

**Comment by dl2n** [comment]
The settings are available in the XML result output (-Rxml). This should be easy enough to parse out into whatever form you would like to save them in. See process-diskspd.ps1 for a powershell example.

Block size from the tested disk - logical and physical sector sizes? This is a reasonable idea, but there are potentially a large number of storage and system configuration elements that would make sense if we went down that path. For now I suggest you simply document/capture that externally.

**Comment by Alfarek** [comment]
Hi Dan,

Thanks for your replay I will try with xml and ps1 example.

Of course I documented them by my own, but I thought it would be nice to have it in disk testing tool I was thinking about only one parameter for start – Bytes per cluster which for SQL is suggested as 64 Kbytes not 4Kbytes as windows default gives.

Anyway thanks for your time and effort about that tool 😊


[https://www.proferis.pl/gfx/proferis/userfiles/admin/tkaleta.png]      Tomasz Kaleta
Wiceprezes
[https://www.proferis.pl/gfx/proferis/userfiles/admin/ikona03.png]      Tomasz.Kaleta@proferis.pl<mailto:Tomasz.Kaleta@proferis.pl>
[https://www.proferis.pl/gfx/proferis/userfiles/admin/ikona02.png]      +48 17 785 22 46
[https://www.proferis.pl/gfx/proferis/userfiles/admin/ikona01.png]      Al. gen. L. Okulickiego 18
35-206 Rzeszów
www.proferis.pl<http://www.proferis.pl>
[https://www.proferis.pl/gfx/proferis/userfiles/admin/logostopka.png]
[krecha-01]

NIP: 5170359010 REGON: 180833967 Kapitał zakładowy w całości wpłacony: 14 000 PLN
KRS: 0000416486 Organ rejestrujący: Sąd Rejonowy w Rzeszowie, XII Wydział Gospodarczy KRS
Uwaga: Wiadomość przeznaczona jest tylko dla jej adresata. Dostęp osób trzecich do tej wiadomości jest zabroniony.
