### ISSUE TITLE
Add HighPriority  Option to -I Parameter

### ISSUE THREAD

**Issue by ale-goncalves** [microsoft/diskspd#127]
When testing with high performance devices (NVMe) synchronous I/O operation show a great difference with Linux based machines with FiO like tests. All Linux based benchmarking is done by setting High Priority for I/O completion, besides IRQ balance and POLL Mode drives. I would like to request to add the HighPriority to -I option which already has very low and low Priority

**Comment by dl2n** [comment]
-I sets the priority hint on the filehandle being used to issue the IO: SetFileInformationByHandle / FileIoPriorityHintInfo with FILE_IO_PRIORITY_HINT_INFO containing a PRIORITY_HINT. This is limited to <= Normal for (all) usermode IO. If you think there is a specific inefficiency in the IO path that > Normal would access for high performance applications that should be available for normal usermode we should take that into our various WG's.
