### ISSUE TITLE
Write IO - LatStdDev

### ISSUE THREAD

**Issue by SteveKeller** [microsoft/diskspd#128]
Hi

Does anybody know what exactly the result of **LatStdDev** means and how to interpret it?

Tested two drives -> Drive D:\ and Drive F:\ on my virtual machine.
Drive D:\ has an average LatStdDev value of 1.3
Drive F:\ has an average LatStdDev value of 2.5
All other result values are equal and the drives are configured the same way.

My Query: diskspd.exe -b64K -o2 -t4 -c20G -d300 -w100 -r -L -Sh testfile.dat

Kind Regard
Steve

**Comment by dl2n** [comment]
It is the standard deviation over the individual IO latencies. The value is a rough indication of their spread - higher values indicate wider variation.
________________________________

**Comment by SteveKeller** [comment]
Great thanks for your explanation!
