### ISSUE TITLE
Really need a local server date/time timestamp in the output

### ISSUE THREAD

**Issue by Jollym** [Microsoft/diskspd#13]
I'm having to do this all manually to all the outputs so it know 3/6/9 months later.

just a -timestamp flag would do it for me.

**Comment by dl2n** [comment]
Good idea, handled in the pending push, located in the <System> block. You'll see some other new stuff alongside.

<System>
<ComputerName>danlo-desk</ComputerName>
<Tool>
<Version>2.0.16b</Version>
<VersionDate>2016/2/22</VersionDate>
</Tool>
<RunTime>2016/03/05 01:03:47 GMT</RunTime>
<ProcessorTopology>
<Group Group="0" MaximumProcessors="12" ActiveProcessors="12" ActiveProcessorMask="0xfff"/>
</ProcessorTopology>
</System>

Confirmed parse with [datetime] constructor.

PS Z:\rs1\sdktools\srvperf\diskspd.oss> $x = [xml](gc .\foo.xml)
PS Z:\rs1\sdktools\srvperf\diskspd.oss> $x.Results.System

ComputerName Tool RunTime                 ProcessorTopology
------------ ---- -------                 -----------------
danlo-desk   Tool 2016/03/05 01:04:03 GMT ProcessorTopology


PS Z:\rs1\sdktools\srvperf\diskspd.oss> $x.Results.System.RunTime
2016/03/05 01:04:03 GMT
PS Z:\rs1\sdktools\srvperf\diskspd.oss> [datetime] $x.Results.System.RunTime

Friday, March 4, 2016 5:04:03 PM

**Comment by dl2n** [comment]
Fixed in 2.0.16b
