### ISSUE TITLE
Error we see: There has been an error during thread execution. Error generating I/O request

### ISSUE THREAD

**Issue by HeddeReinert** [microsoft/diskspd#130]
We are running the command in the amd64 subdirectory:  Here is the screen output:
![image](https://user-images.githubusercontent.com/51829696/74439512-fa6c7f80-4e31-11ea-84e8-75e11e35cccf.png)
This is what we see in the log file:

Command Line: diskspd –b8K –d30 –o4 –t8 –h –r –w25 –L –Z1G –c20G F:\iotest.dat

Input parameters:

	timespan:   1
	-------------
	duration: 10s
	warm up time: 5s
	cool down time: 0s
	random seed: 0
	path: '–b8K'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–d30'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–o4'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–t8'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–h'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–r'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–w25'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–L'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–Z1G'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: '–c20G'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal
	path: 'F:\iotest.dat'
		think time: 0ms
		burst size: 0
		using software cache
		using hardware write cache, writethrough off
		performing read test
		block size: 65536
		using sequential I/O (stride: 65536)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 1
		using I/O Completion Ports
		IO priority: normal

System information:

	computer name: SQLPRD01B
	start time: 2020/02/13 01:14:43 UTC

Results for timespan 1:
*******************************************************************************
The test was interrupted before the measurements began. No results are displayed.

**Comment by DanPear** [comment]
It looks as if all the hyphens in the command line have been replaced. Try typing it out again. PowerShell will allow the use of different style dashes but the Command Prompt will not.
