### ISSUE TITLE
[QUESTION] Writing complete random data to the disk using DiskSpd

### ISSUE THREAD

**Issue by swarooptk** [microsoft/diskspd#137]
To begin with, this is not a bug , but rather a question - posting it here, since I could not find other way to reach out to the community

I'm trying to test the I/O workload on a Disk which has de-duplication enabled.When I am using diskspd with complete random write workload for 5 minutes (### diskspd.exe -r -w100 -Sh -d300 ### ) on this disk,  the data is getting de-duped. 
(and I do not want to switch-off dedup on this disk, as my test requires to be on)

I'm trying to find if diskspd generates complete random and unique data, so that the de-dup will not be performed - Any help here is highly appreciated. 

Thanks.

**Comment by DanPear** [comment]
You can use the -Z\<size> option which is documented under the [Command line and parameters](/microsoft/diskspd/wiki/Command-line-and-parameters) section to achieve what you want. Also, issue #126 goes into more detail on using the option.

**Comment by krishnasw** [comment]
Thank you @DanPear for your inputs - I started using -Z<size> option and seeing the dedup not kicking in. 
I do have  one more question - Should I try to set the size value in the -Z parameter according to the size of the disk? In other words, if I allocate more size for -Z , will I get more random data? 
Thank you.

**Comment by dl2n** [comment]
-Z<size> specifies the size of a memory buffer, random filled, randomly sampled from at 512B boundaries for write source buffers.

We would generally expect < 50MB to be enough, but it all depends on the aggressiveness of your dedup subsystem. If you find yourself actually needing large amounts to defeat the dedup (>500MB might be a good break point), consider the -Zr option which uses an inexpensive randomizer to generate per-IO random buffer fill. While its inexpensive it does come at a detectable CPU cost to be aware of.

**Comment by ptr727** [comment]
The -c option appears to create highly compressible files.
I found that on ZFS with LZ4 a 2GB test file is 65MB on disk.
I tried combining -Zr with -c, but it does not appear to make a difference.

In my own tests I create my test files using per write random buffers, e.g. a 64GB file is ~64GB on disk.
I know for COW this does not really matter for write tests, but it does matter for read tests such that IO is performed for read not just decompression.

**Comment by dl2n** [comment]
Generally, the recommendation will be to pre-season a created file with a data pattern appropriate to workload in cases like this. This means running a load on the file ahead of the measured run with the desired data pattern (-Z<options>). I suspect you ran load for a relative brief period of time and did so from an administrative context – if you ran longer (more file coverage), it would be pretty surprising if -Zr could be trivially defeated.

DISKSPD will create the file in one of two initial states depending on the privilege of the invoking user/session.


  *   Non-Administrator: a “WARNING” message will be shown (below, from IORequesteGenerator.cpp), and the file will be written sequentially through with the default byte pattern of 0x00 0x01 0x02 … 0xff repeating.
  *   Administrator: no WARNING or other output, and the file will be created with the valid data length (VDL) set at EOF (see SetFileValidData)

        {
            PrintError("WARNING: Could not set valid file size (error code: %u); trying a slower method of filling the file"
                       " (this does not affect performance, just makes the test preparation longer)\n",
                       GetLastError());
            fSlowWrites = true;
        }

These two cases are indeed somewhat dated functionally, when most storage was rotating HDD without additional drive metadata – the goal was a quick way of guaranteeing device media access, without the filesystem overhead of VDL extension. It requires more awareness for SSD and compressing storage systems.

So, as admin context DISKSPD would create an effectively zero-fill file and with a brief run a limited amount of data would be placed into it.

Let me know if this doesn’t explain it, and if so what your command line invocation(s) are.

**Comment by ptr727** [comment]
Thank you for the details.

I am doing synthetic benchmarks to test SMB performance, so no actual data file to test.
I ended up writing my own file prep code that will write random data, similar to how I expected -c and -Zr could work. This results in a file with on disk and logical sizes near equal on ZFS with LZ4.

As for SetfileValidData(), my understanding is that it will no zero fill the file, but use whatever data is already on disk, i.e. why the special SE_MANAGE_VOLUME_NAME privilege is required for it may expose previously discarded file data?

Anyway, that is not required on COW filesystems, where I simple seek and end of file is sufficient, so this does work over SMB without any special privileges:

```csharp
        public static bool CreateRandomFilledFile(string name, long size)
        {
            try
            {
                // Create the file
                using FileStream stream = File.Open(name, FileMode.Create, FileAccess.ReadWrite, FileShare.ReadWrite);

                // Set the file length, this has no real impact on COW filesystems
                stream.SetLength(size);
                stream.Seek(0, SeekOrigin.Begin);

                // Buffer with random data
                const int buffersize = 2 * Format.MiB;
                byte[] buffer = new byte[buffersize];
                Random rand = new Random();

                // Write in buffer chunks
                long remaining = size;
                while (remaining > 0)
                {
                    // Fill buffer with random data
                    rand.NextBytes(buffer);
                    // Write
                    long writesize = Math.Min(remaining, Convert.ToInt64(buffer.Length));
                    stream.Write(buffer, 0, Convert.ToInt32(writesize));
                    // Remaining
                    remaining -= writesize;
                }

                // Close
                stream.Close();
            }
            catch (Exception e)
            {
                ConsoleEx.WriteLineError(e);
                return false;
            }
            return true;
        }

        public static bool CreateSparseFile(string name, long size)
        {
            try
            {
                // Create the file
                using FileStream stream = File.Open(name, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite);

                // Set length
                stream.SetLength(size);

                // Close
                stream.Close();
            }
            catch (Exception e)
            {
                ConsoleEx.WriteLineError(e);
                return false;
            }
            return true;
        }
```

See: https://github.com/ptr727/DiskSpeedTest

**Comment by dl2n** [comment]
It would indeed be nice if DISKSPD had a pre-writing mode similar to what you have here. In full form I would implement it similar to FIO’s loops option, which would allow simple seasoning per the SNIA SSD specs which suggest twice-through sequential rewrite prior to characterization.

The detail to be aware of is that -c only creates the file (always – it will delete/recreate an file) and leaves it in one of the two states I mentioned. Any data produced into it beyond that is due to measured runs. That means awareness of how much data in what pattern, etc. Since DISKSPD only works on time intervals – run for N seconds – we have to adjust to the rate at which data is being written in order to season effectively.

i.e., running for -b4k -r -d30 (seconds) will only have written a small amount of data.

Yes, you’re right, I was oversimplifying SetFileValidData. What its doing is removing the filesystem’s VDL protection against reading previously written data. What you get is dependent on device behavior when the sectors are read – that was my comment about device metadata. If its an SSD, TRIM is active or the SSD is in FOB state (fresh-out-of-box), it may be optimized zeroes w/o access to the media.

**Comment by swarooptk** [comment]
Thanks @dl2n and @DanPear  for your answers and explanation

**Comment by dl2n** [comment]
Closing old issue.
