### ISSUE TITLE
This application has requested the Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by Rajchau** [Microsoft/diskspd#14]
Environment: VM on VMWare, Windows 2012 R2 Standard 64bit, 8 CPUs, 24 GB RAM, R drive 64K sector size, X drive 64K sector size.
Created folders named DiskSPD in R drive and DiskSPDResults in X drive.
Downloaded Diskspd-v2.0.15, extracted files in X drive and ran command as follows from DOS in admin mode.
X:\Diskspd-v2.0.15\amd64fre>diskspd -b8K -d60 -h -L -o8 -t8 -r -W -w50 -Z20G -c50G R:\diskspd\test.dat > X:\DiskSPDResults\R_resultssql_1.txt

Error: This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

Please help.

**Comment by Rajchau** [comment]
The issue is happening specifically on two servers which had mount points in drives. The drives were removed and mount points were promoted to drive names. The utility started failing after the mount points were converted into drives. It has been running fine on other servers.

**Comment by dl2n** [comment]
If you can get a process dump, I'd be curious to look at it.

-Z20G is vastly larger than necessary to get a good random source buffer. DISKSPD will index the random buffer at 4byte offsets, at random, to produce write source buffers. A 1MB buffer would produce 261,120 different 4KB buffers.

    PS C:\Users\danlo> (1MB-4KB)/4
    261120

Unless we got very unlucky every one would be unique. All we need to do is defeat realtime dedup and/or compression if we know it is present - a few 10s of MB would be plenty. GB is extremely large.
