### ISSUE TITLE
Error Code 53 (What is it and why isn't there a list of error codes and their meaning anywhere?)

### ISSUE THREAD

**Issue by Moore-Connor** [microsoft/diskspd#140]
Hi!

I've been trying to use diskspd.exe to run some tests for our new file server. I've been trying to test writing to a server share but whenever I run the tool I run into error 53. I went hunting for the error code and have found nothing so far.

If someone could tell me what the error is or if there is a list of error codes and their meaning (if not it's not a bad idea). I'd be much appreciated.

Command being run from Client Laptop (CL01) to File Server (FS01):
diskspd.exe -c10G -d30 -b64k -Sh -o32 -t4 -r -w100 \\FS01\Test\tempfile.dat

**Comment by DanPear** [comment]
You can see the description for certain Windows error codes using the following command:

```
C:\>net helpmsg 53
The network path was not found.
```

Is this case it appears as if you're only using a single backslash to reference the remote server.

**Comment by Moore-Connor** [comment]
So they do follow Windows error codes, gotcha.

That was just a typo since I didn't copy and paste whoops.

Knowing the error code is enough though. Thank you
