### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by sada-kubsad** [microsoft/diskspd#145]
Hi
When building on RHEL 7 with all dependencies met, we get this error: 

$ make
src/result_formatter.cc: In member function ‘virtual void diskspd::ResultFormatterText::output_results(const diskspd::Profile&)’:
src/result_formatter.cc:107:48: error: variable-sized object ‘cpu_usage_totals’ may not be initialized
    double cpu_usage_totals[num_cpu_fields] = {0};

Can someone please guide us how to resolve this build error?

Best Regards
Sada Kubsad

**Comment by DanPear** [comment]
Please use the [diskspd-for-linux](https://github.com/microsoft/diskspd-for-linux) project for Linux related issues.
