### ISSUE TITLE
Where can I find Diskspd version 2.0.17a

### ISSUE THREAD

**Issue by sukpia** [microsoft/diskspd#150]
Hello, may I know where can I find the binary for Diskspd version 2.0.17a.

**Comment by dl2n** [comment]
We do not have an archive back to 2.0.17a. If there is a specific question or concern you have with 2.0.17a v. the current release, please let us know?

**Comment by sukpia** [comment]
Thanks. I ran into problem when using v2.0.21a and my co-worker told me that she is using v2.0.17a with no issue. Turn out it is not the version differences that caused the issue. 
I am trying to run a performance test on write operation on a few hard drives with the following command
`diskspd.exe -a0 -b512k -w100 -t1 -o1 -Suw -L -Z256M -W0 -d180 -C0 #2 >> C08U08_drive2_seq_write.txt`
However, it gave the following error:

_t[0] error during write error code: 5)
There has been an error during threads execution
Error generating I/O requests_

After reading your wiki, i realize that it is recommended to remove filesystem and partition when performing write operation. By doing that, i can successfully run the test now. So is it correct that the write operation cannot be done on a formatted hard drive?

**Comment by dl2n** [comment]
This does come up frequently enough that a more targeted error diagnostic would be useful, time permitting.

A formatted filesystem will normally block write operations to the raw device. In normal operation this prevents accidentally destroying the formatted content on the device.

If your intent is to do write performance work on the device, removing the FS/partition is the correct thing to do. If you want to do performance work through the filesystem you should create a file to use as the target.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
