### ISSUE TITLE
Get-FleetVolumeEstimate -Cluster XYZ throws errors

### ISSUE THREAD

**Issue by jaromirk** [microsoft/diskspd#157]
![image](https://user-images.githubusercontent.com/9829838/134888190-de1b63a1-2eb2-4372-bdf5-a66cd80c7aca.png)

**Comment by dl2n** [comment]
Acknowledging.  I'll try to sort out what could be going on shortly.

**Comment by dl2n** [comment]
This is fixed in 2.0.2.

**Comment by jaromirk** [comment]
FYI.. 
![image](https://user-images.githubusercontent.com/9829838/142671611-ddd23033-c649-45c1-a9c8-7ea8949ba5ba.png)
