### ISSUE TITLE
Show-Fleet -Cluster XYZ shows error

### ISSUE THREAD

**Issue by jaromirk** [microsoft/diskspd#158]
![image](https://user-images.githubusercontent.com/9829838/134901157-242f96b5-6ff9-41a0-8cf9-cb4d66f9e055.png)

**Comment by dl2n** [comment]
Acknowledging. I'll try to sort out what could be going on shortly. This one looks simple.

**Comment by dl2n** [comment]
Fix will be in the next push.

**Comment by dl2n** [comment]
This is fixed in 2.0.2.
