### ISSUE TITLE
Running on SSD gives error: ERROR: Could not obtain partition info (error code: 1)

### ISSUE THREAD

**Issue by The-MAZZTer** [Microsoft/diskspd#16]
Error appears to be generated from the call to DeviceIoControl on line 81 in. [IORequestGenerator/IORequestGenerator.cpp](https://github.com/Microsoft/diskspd/blob/master/IORequestGenerator/IORequestGenerator.cpp)

Error code 1 is ERROR_INVALID_FUNCTION.

I have an up-to-date Windows 10 machine. Running x86 and amdx64 both give the same result. The error only occurs if I try to use diskspd on my SSD, other drives have no issue.

Drive is a Samsung SSD 850 EVO 1TB. I'm using a standard Microsoft driver for it (driver details reports disk.sys, EhStorClass.sys, and partmgr.sys are the files for the driver) at version 10.0.10586.0.

**Comment by dl2n** [comment]
Sorry I missed this when it was first filed. Is this still reproducing?

**Comment by The-MAZZTer** [comment]
Yes. Diskspd version number is 2.0.15 (2015/01/09)

**Comment by dl2n** [comment]
I'm asking around. In the meantime, can you try against the physical device as opposed to the <driveletter>:?

get-volume c | get-partition | get-disk

And use #<disk number> as the target. If in powershell, quote the #, ala `#20

**Comment by The-MAZZTer** [comment]
Using #0 (which get-volume c | get-partition | get-disk reports is the number of the SSD drive letter) works.

**Comment by dl2n** [comment]
Fixed in the 2.0.18a push. DISKSPD was using a very old IOCTL to query out the partition size, one which only worked for MBR, not GPT.
