### ISSUE TITLE
Remove-Fleet does not re-enable CSV Balancer

### ISSUE THREAD

**Issue by jaromirk** [microsoft/diskspd#160]
After removing feelt with Remove-Fleet, CSV Balancer remains 0

(Get-Cluster $ClusterName).CsvBalancer

**Comment by JimLin-Qcttw** [comment]
the default value is 0 of CsvBalancer on my lab.

**Comment by jaromirk** [comment]
Fresh install? I just installed fresh AzSHCI 20H2 cluster and default value is 1.

**Comment by dl2n** [comment]
I believe this has changed over releases; I will check and get back.

**Comment by dl2n** [comment]
I'm able to confirm that as of Server 2019/based products that CsvBalancer is automatically disabled when S2D is enabled. This is due to the cost of read cache rebuild if CSVs are freely relocated in the cluster.

@jaromirk : when did you look during the process of installation with 20H2?

**Comment by jaromirk** [comment]
Gosh, big facepalm. Of course you are right, CSV Balancer is disabled. I was under impression it was enabled before and I did check **before** enable-clusterS2D.

**Comment by dl2n** [comment]
Thanks for confirming
