### ISSUE TITLE
Measure-FleetCoreWorkload - Method invocation failed

### ISSUE THREAD

**Issue by MartinRas** [microsoft/diskspd#161]
Method invocation failed because [System.Management.ManagementObject] does not contain a method named
'RefreshRegParams'.
At C:\Program Files\WindowsPowerShell\Modules\VMFleet\2.0.0.1\VMFleet.psm1:8197 char:13
+             $r = Invoke-Command -session $s {
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (RefreshRegParams:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : XXXXX

![image](https://user-images.githubusercontent.com/37659391/136525853-b08d3628-0af2-4047-ab55-00470346e4ad.png)

**Comment by dl2n** [comment]
This is understood. I am reverifying Server 2019 and should have a fix for this up in the next few days.

In the meantime you can comment out the calls to SetCacheBehavior in VMFleet.psm1. The method we use for accelerating read cache warmup only applies to Server 2022+.

**Comment by MartinRas** [comment]
@dl2n Thanks!

**Comment by dl2n** [comment]
This is fixed in 2.0.2 - RS5 is now supported and confirmed to work.
