### ISSUE TITLE
api-ms-win-core-libraryloader-l1-2-1.dll is missing

### ISSUE THREAD

**Issue by burgonyapure** [Microsoft/diskspd#163]
Environment: Windows Server 2012 R2 Build 9600

Error when trying to run diskspd.exe
![image](https://user-images.githubusercontent.com/37111016/136934120-fbf0c5e1-cff6-4f6c-80aa-8487b9432962.png)

**Comment by burgonyapure** [comment]
> I found if I used the older version of DiskSpd 2.0.21 I was able to get past this issue.

Yeah that one is fine for me also.
I'd wanted to use the new xml functionality where I can run it like:
```
diskspd.exe -t12 -o32 -r4k -w0 -d30 -Sh -D -L -c5G -Rpxml .\IO.dat > .\profile.xml
diskspd.exe -X'profile.xml' > .\bench.xml
```
And this works on my pc with Windows10 ver.1909 18363.1801 build
But sadly not with win server 2012 r2

**Comment by JimLin-Qcttw** [comment]
I use visual studio 2019 to compile diskspd version 2.1.0.0 and it works on the Windows Server 2012 R2 Build 9600.

**Comment by corower** [comment]
getting same error with latest (? 2.1)  pre-compiled version.
win2008 R2 standard, SP1. 

:(
