### ISSUE TITLE
The Program Can't Start

### ISSUE THREAD

**Issue by pravinlpatel** [microsoft/diskspd#165]
Hi Team,

I am getting following error while running diskpd. Any lead?

CC: @DanPear @dl2n

**Comment by dl2n** [comment]
Please post the error here and tell us what os version/architecture it is occurring on. If it is with a pre compiled binary please verify and indicate which one; if compiled yourself, what tool chain were you using?

**Comment by pravinlpatel** [comment]
Hi @dl2n,

Apology. Somehow the error screen link is removed but let me confirm you about specs.

I am trying to run latest version of diskpd on windows server 2012 R2 from amd64 folder but it is ending up with an Following error.

the program can't start because api-ms-win-crt-runtime-l1-1-0.dll

**Comment by dl2n** [comment]
This has been reported in another issue. If you can compile from source on an appropriate toolchain this will get you going.

I am working on root causing the issue with the build toolchain I used, but this may take some time.

**Comment by kscheel** [comment]
I just ran into the same problem. The previous release from 2018 worked fine though: https://github.com/microsoft/diskspd/releases/tag/v2.0.21a

**Comment by vavdoshka** [comment]
yes same here with `2.1`
<img width="489" alt="image" src="https://user-images.githubusercontent.com/11683992/172455575-7d20469a-28b1-4e01-9478-0dd8f7075296.png">

`2.0.21a` works ok

**Comment by 110142-PabloRomero** [comment]
> yes same here with `2.1` <img alt="image" width="489" src="https://user-images.githubusercontent.com/11683992/172455575-7d20469a-28b1-4e01-9478-0dd8f7075296.png">
> 
> `2.0.21a` works ok

Excelent, this solution worked for me!! Thank you

**Comment by dl2n** [comment]
Downlevel operation for the binary package should be addressed in the latest version (2.2) which we just released.
