### ISSUE TITLE
Move-Fleet -Cluster $ClusterName does not work

### ISSUE THREAD

**Issue by jaromirk** [microsoft/diskspd#166]
Get-ClusterGroup is querying local machine and not remote cluster.

Thank you!

![image](https://user-images.githubusercontent.com/9829838/140526898-0ce82fd1-89c8-4d66-a62f-1683e6d84dc6.png)

**Comment by dl2n** [comment]
Thanks for reporting.

The Get-Volume issue is fixed in the most recent 2.0.2 push. I'll get the Get-ClusterGroup issue very shortly.

**Comment by dl2n** [comment]
Please update to 2.0.2.1 (just pushed today, 11/9). Thanks for the issue report.
