### ISSUE TITLE
Start-FleetSweep -Cluster $ClusterName fails collecting results

### ISSUE THREAD

**Issue by jaromirk** [microsoft/diskspd#167]
Not sure what might be wrong. It receives only slightly more than half results

Start-FleetSweep -Cluster $ClusterName -b 4 -t 4 -o 4 -w 0 -d 60 -p r -Warm 10 -Cool 10

![image](https://user-images.githubusercontent.com/9829838/140529519-f0459ea6-01cf-40fc-abeb-befb7b929143.png)

**Comment by dl2n** [comment]
Especially if this was an RS5 cluster it is likely I've addressed that with the 2.0.2.x update shortly. For the Get-Cluster error - did the cluster crash/restart in the middle of the run?

**Comment by jaromirk** [comment]
Not sure if it was AzSHCI 20H2 or 21H2 :). I'm redeploying clusters too often... Will test it. Cluster was up and running.

**Comment by dl2n** [comment]
Please update to 2.0.2.1 (just pushed today, 11/9), this will definitely address RS5 issues and may/may not address other timing related bumps. Thanks.

**Comment by dl2n** [comment]
Please reopen or file a new issue if needed. Hopefully I straightened out the blocking issue with 2.0.2.1 in 2.0.2.2; sorry for the back and forth.
