### ISSUE TITLE
Measure-FleetCoreWorkload - The running command stopped...

### ISSUE THREAD

**Issue by gjvanzyl** [microsoft/diskspd#168]
Newly built fleet on Windows Server 2019 throwing error after write warm-up.

2021-11-08T19:29:44: WRITE WARMUP COMPLETE: took 00d.01h:54m:12s
VERBOSE: Operation '' complete.
2021-11-08T19:29:53: READ CACHE WARMUP: START
VERBOSE: 2021-11-08T19:29:53: 6 cache devices totaling 34,76 TiB capacity
VERBOSE: 2021-11-08T19:29:53: 144 VMs => 148,32 GiB cache available per VM (at 60,0% target of total)
VERBOSE: 2021-11-08T19:29:53: Profile read range: [0,00GiB - 57,50GiB] (57,50GiB total) of total 57,50GiB VM workingset
VERBOSE: 2021-11-08T19:29:53: Full range warmable
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
VERBOSE: 2021-11-08T19:29:54: pause is already set @ 11/08/2021 19:29:44
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'RefreshRegParams'."

**Comment by dl2n** [comment]
This should be fixed in 2.0.2 - can you update? Please Install-Fleet -Force after installing the new module - this places the new VM control loop script for VM pickup.
