### ISSUE TITLE
 Start-FleetResultRun -ProfileXml $profile - The property 'Latency' cannot be found on this object

### ISSUE THREAD

**Issue by gjvanzyl** [microsoft/diskspd#169]
PS C:\Windows\system32> $profile = Get-FleetProfileXml -Name "General" -Warmup 30 -Duration 180 -Cooldown 30 -WriteRatio 0 -BlockSize 8
PS C:\Windows\system32>Start-FleetResultRun -ProfileXml $profile -Verbose
VERBOSE: 2021-11-08T20:00:04: removing QoS Policy
VERBOSE: Connecting to cluster on local computer HCI01B.
VERBOSE: 2021-11-08T20:00:18: <Profile>
  <Progress>0</Progress>
  <ResultFormat>xml</ResultFormat>
  <Verbose>false</Verbose>
  <TimeSpans>
    <TimeSpan>
      <CompletionRoutines>false</CompletionRoutines>
      <MeasureLatency>true</MeasureLatency>
      <CalculateIopsStdDev>true</CalculateIopsStdDev>
      <DisableAffinity>false</DisableAffinity>
      <Duration>180</Duration>
      <Warmup>30</Warmup>
      <Cooldown>30</Cooldown>
      <IoBucketDuration>1000</IoBucketDuration>
      <RandSeed>0</RandSeed>
      <Targets>
        <Target>
          <Path>*1</Path>
          <BlockSize>8</BlockSize>
          <DisableOSCache>true</DisableOSCache>
          <WriteThrough>true</WriteThrough>
          <WriteBufferContent>
            <Pattern>random</Pattern>
            <RandomDataSource>
              <SizeInBytes>10485760</SizeInBytes>
            </RandomDataSource>
          </WriteBufferContent>
          <ThreadStride>0</ThreadStride>
          <RequestCount>32</RequestCount>
          <WriteRatio>0</WriteRatio>
          <Throughput>0</Throughput>
          <ThreadsPerFile>1</ThreadsPerFile>
          <IOPriority>3</IOPriority>
          <StrideSize>8</StrideSize>
        </Target>
      </Targets>
    </TimeSpan>
  </TimeSpans>
</Profile>
VERBOSE: Connecting to cluster on local computer HCI01B.
VERBOSE: Connecting to cluster on local computer HCI01B.
2021-11-08T20:00:19: START Go Epoch: 2
2021-11-08T20:00:19: CLEAR pause at Go
VERBOSE: 2021-11-08T20:00:19: pause cleared @ 11/08/2021 20:00:19
VERBOSE: logman create @ HCI01C : The command completed successfully.
VERBOSE: logman create @ HCI01B : The command completed successfully.
VERBOSE: logman create @ HCI01A : The command completed successfully.
VERBOSE: logman start @ HCI01B : The command completed successfully.
VERBOSE: logman start @ HCI01A : The command completed successfully.
VERBOSE: logman start @ HCI01C : The command completed successfully.
2021-11-08T20:00:22: SLEEP TO RUN CHECK (17,30 seconds)
2021-11-08T20:00:39: RUN CHECK Go Epoch: 2
2021-11-08T20:00:41: RUN CHECK 1 : 0/144 done (2,16s, total 2,16s)
2021-11-08T20:00:41: RUN CHECK PASS Go Epoch: 2
2021-11-08T20:00:41: SLEEP TO END (217,82 seconds)
VERBOSE: logman stop @ HCI01B : The command completed successfully.
VERBOSE: logman delete @ HCI01B : The command completed successfully.
VERBOSE: xcopy @ HCI01B : 1 File(s) copied
VERBOSE: logman stop @ HCI01A : The command completed successfully.
VERBOSE: logman stop @ HCI01C : The command completed successfully.
VERBOSE: logman delete @ HCI01C : The command completed successfully.
VERBOSE: xcopy @ HCI01C : 1 File(s) copied
VERBOSE: logman delete @ HCI01A : The command completed successfully.
VERBOSE: xcopy @ HCI01A : 1 File(s) copied
2021-11-08T20:06:11: COMPLETION CHECK 1 : 144/144 done (1,77s, total 1,77s)
VERBOSE: Connecting to cluster on local computer HCI01B.
VERBOSE: Initiating untargeted move for group 'Cluster Virtual Disk (collect)'.
VERBOSE: Moved group 'Cluster Virtual Disk (collect)' from HCI01A to HCI01C.
ReduceDISKSPDResultToRowResult : The property 'Latency' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\VMFleet\2.0.0.1\VMFleet.psm1:6073 char:41
+ ...   $row = @(Get-ChildItem $resultPat | ReduceDISKSPDResultToRowResult)
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ReduceDISKSPDResultToRowResult], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,ReduceDISKSPDResultToRowResult

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Fleet VM throwing Error

![image](https://user-images.githubusercontent.com/93940674/140795563-deceff87-d352-49f5-941b-d69a4d76fe41.png)

**Comment by dl2n** [comment]
Can you confirm the presence of c:\run\testfile1.dat in the VM as well as show the output of "Get-Disk | fl *"? If you had a pre-release version of the module you may need to Install-Fleet -Force to update the VM control script; this is safe to do, regardless.

You can copy content from the VM to the host via the L: drive mapping -> (in host terms) C:\ClusterStorage\collect\control that should be present. This will make it easier to get the Get-Disk output, e.g. in the VM:

Get-Disk | fl * > L:\gd.txt

**Comment by gjvanzyl** [comment]
Thanks. I have updated to 2.0.2.1 but my fleet seemed to be malfunctioning. Executed "Remove-Fleet", "Install-Fleet -Force" but now having issues with New-Fleet. Logging separate issue.
