### ISSUE TITLE
Tool does not execute properly when run in succession.

### ISSUE THREAD

**Issue by manuks88** [Microsoft/diskspd#17]
2 machines are required for this test. One acting a SMB server where a test file of 3GB is created on a PCI SSD. From the client start write test followed by read test over a 10Gbps Network interconnect.

Command used : 
diskspd.exe -w100 -n -L -W0 -d10 -t8 -o16 -b32k -si32k -S \10.1.1.56\wshare1\testfile1.dat > a.txt
diskspd.exe -w0 -n -L -W0 -d10 -t8 -o16 -b32k -si32k -S \10.1.1.56\wshare1\testfile1.dat > b.txt

Copy pasted the commands in a batch file and ran it. For the write test I get line rate of 9.4Gbps. 
But for read I get 3Gbps.
The test can be sequential or random and the result is same.

When the same test is run using sqlio2 I don't see the issue and both read and write give line rate.
sqlio2 -s10 -t8 -o16 -b32k -fsequential -T0 -LS -BN \10.1.1.56\wshare1\testfile1.dat > a.txt
sqlio2 -s10 -t8 -o16 -b32k -fsequential -T100 -LS -BN \10.1.1.56\wshare1\testfile1.dat > b.txt

Diskspd Tool versions used : 
1. version 2.0.16b (2016/2/22)
2. version 2.0.15 (2015/01/09)

SQLIO Tool Version : 
sqlio v2.15. 64bit_SG

**Comment by dl2n** [comment]
I agree the cmdlines are ~equivalent.

Two minor differences.

First, in this case, is that SQLIO is generating a random write buffer of 20MiB as source for its writes. By default DISKSPD uses a nonzero but highly compressible pattern (see /?). With DISKSPD you would use -Z20M for the equivalent to SQLIO.

Second, SQLIO uses completion routines while DISKSPD defaults to completion ports. I do not expect that to have a negative effect, but see -x.

The more important difference in behavior is that DISKSPD affinitizes its threads to specific cores by default. On a multi-socket system Windows will roughly round robin each successive process launched between sockets. If you got (incredibly, I'll admit) unlucky with both NUMA cost and collision with something else contending for the core, that's about the only thing I can think of.

As a first step, pass -n to disable hard affinity. If that doesn't do it, start looking at CPU distribution in TaskMgr and see if something jumps out. Go ahead and try -x and -Z20M but I'll be surprised if those contribute.

Might also be worth running locally on the server and comparing results again there.

**Comment by manuks88** [comment]
Hi Dan, I have already used the "-n"  in the test. 
I tried with "-x" option and on read test machine is hitting an assert with "STATUS_BREAKPOINT_BLOCK_heap_corruption!heap_corruption". 
With "-Z20M" the symptom is same as what I described in the original description.

**Comment by dl2n** [comment]
Sorry for the delay in coming back.

Do you get the same behavior locally on the target server vs. the same storage, or does it only happen over SMB?

Re: NUMA, you should eyeball the specific cores being hit in Task Manager/equivalent. While the scale of the effect is way outside what I'd expect NUMA effect to be, like I sad Windows does round-robin processes between NUMA nodes and a *single* execution of -n (or -ag on 2.0.15) will be random on a multi-KGROUP system.

**Comment by DanPear** [comment]
Closing this off as it doesn't appear to be reproducible and there have been no other reports made. If in the future further information is available the please feel free to comment.
