### ISSUE TITLE
Launch Diskspeed impossible on Windows Server 2012 R2

### ISSUE THREAD

**Issue by bartounet16** [microsoft/diskspd#179]
Hello.
When i try to launch Diskpeed last version i have this error message

not found api-ms-core-libraryloader-I1-2-1.dll

![image](https://user-images.githubusercontent.com/1244020/152856061-36eab6c8-bb8f-4fe2-a4e3-ca78f32bd39e.png)

**Comment by dl2n** [comment]
Downlevel binary operation was addressed in the 2.2 release.
