### ISSUE TITLE
( Import-Counter) The data is not valid

### ISSUE THREAD

**Issue by ZoomImpulse** [microsoft/diskspd#187]
Hi I'm getting the following error

TerminatingError(Get-Counter): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The data is not valid."

Any idea what might be wrong here?

[coreworkload.log](https://github.com/microsoft/diskspd/files/9349871/coreworkload.log)

**Comment by dl2n** [comment]
Does the following command return an error?

```
get-counter -ListSet 'Cluster CSVFS'
```
