### ISSUE TITLE
Bad sample on wiki page

### ISSUE THREAD

**Issue by brettjacobson** [microsoft/diskspd#195]
The sample presented on the [wiki](https://github.com/microsoft/diskspd/wiki/Sample-command-lines) for "Mix random and sequential workloads (20% random and 80% sequential I/O)" results in an error:

> ERROR: use -r to specify IO alignment when using mixed random/sequential IO (-rs)

Adding any kind of `-r` option results in:

> ERROR: sequential IO (-s) conflicts with random IO (-r/-rs)

Is there a way to execute a mix of sequential and random workloads?

**Comment by dl2n** [comment]
Sorry for the delay seeing this. That was a typo on the example - the -s8b should have been -r8b. I've fixed the text.
