### ISSUE TITLE
Error message in the log file - diskspd

### ISSUE THREAD

**Issue by daem0nk3rn3l** [microsoft/diskspd#200]
This is the command I'm running:
diskspd.exe -d60 -W15 -C15 -c128M -t4 -o4 -b8k -L -r -Sh -w50 d:\temp\Diskspd\diskspeedtest.dat

And I get the error message:
Error opening file: i [2]
There has been an error during threads execution
Error generating I/O requests

It runs and I get output, but in the log file I get the above.  
I am running in elevated mode.
Can this be ignored?

**Comment by dl2n** [comment]
Error 2 is file not found; we should definitely get around to translating those to text.

Does the file exist after that error & the run finishes? And do you only get _one_ of those errors, not four? That is coming from the load thread trying to open the file, so with -t4 there are four.

**Comment by daem0nk3rn3l** [comment]
> Error 2 is file not found; we should definitely get around to translating those to text.
> 
> Does the file exist after that error & the run finishes? And do you only get _one_ of those errors, not four? That is coming from the load thread trying to open the file, so with -t4 there are four.

Yes the text file is produced once the code is finished.

Would you like me to publish the code?

**Comment by daem0nk3rn3l** [comment]
> Error 2 is file not found; we should definitely get around to translating those to text.
> 
> Does the file exist after that error & the run finishes? And do you only get _one_ of those errors, not four? That is coming from the load thread trying to open the file, so with -t4 there are four.
Yes the text file is produced once the code is finished.

Would you like me to publish the code?

**Comment by dl2n** [comment]
Yes, please upload the text result from DISKSPD.

**Comment by dl2n** [comment]
Please reopen if you can provide the result file to analyze, thanks.
