### ISSUE TITLE
the source code can not be complied?

### ISSUE THREAD

**Issue by queclink** [Microsoft/diskspd#210]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “TraceLoggingProvider.h”: No such file or directory	IORequestGenerator	h:\files\diskspd-master2.2\diskspd-master\common\common.h	36	

Has anyone encountered a similar problem? Thank you.

**Comment by dl2n** [comment]
ETW is a standard part of the Windows SDK. Make sure you've got a current one installed - go to the Visual Studio Installer, `Modify` your installation and make sure you've got `Desktop development with C++` selected. In the detail view on the right you should see `Windows 10/11 SDK (v x.y.z)` options, at least one of which needs to be selected - for instance the latest Windows 11 SDK.

On my system its installed here:

`C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared`

**Comment by queclink** [comment]
Thank you very much for your help.
So far, I am able to compile the *lib file on my computer, but I still don't know how to compile the diskspd32 program?
could you give me some suggestion,thanks.

![disk_spd_lib](https://github.com/microsoft/diskspd/assets/43567233/bc89353b-b66c-4328-98d7-fb489ea5dc1a)

**Comment by dl2n** [comment]
You should be building the entire solution, not each individual sub-project independently; diskspd.exe itself (it is not "diskspd32") is produced out of the cmdrequestcreator project. I see you've got CmdLineParser and IORequestGenerator ... keep going.

**Comment by dl2n** [comment]
Assuming this was addressed. Please reopen if you need more help.
