### ISSUE TITLE
Spdk21.01 version, after configuring the virtual machine qemu with vhost user blk pci, the corresponding block device is abnormal when the virtual machine is up

### ISSUE THREAD

**Issue by wwwwxxxxhhhh** [Microsoft/diskspd#211]
XML information of virtual machines
    <qemu:arg value='socket,id=vhost.0,path=/var/tmp/vhost.0'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='vhost-user-blk-pci,addr=0xf,chardev=vhost.0,id=vhost.0,bus=pci.0,num-queues=2'/>
    
The error message is as follows：
Jun 26 14:06:52 localhost spdk[25901]: VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
Jun 26 14:06:52 localhost spdk[25901]: VHOST_CONFIG: vring call idx:0 file:35
Jun 26 14:06:52 localhost spdk[25901]: VHOST_CONFIG: virtio is now ready for processing.
Jun 26 14:06:52 localhost spdk[25901]: rte_vhost_compat.c:  81:vhost_session_mem_register: *WARNING*: Failed to register memory region 0. Future vtophys translation might fail.
Jun 26 14:06:52 localhost spdk[25901]: rte_vhost_compat.c:  81:vhost_session_mem_register: *WARNING*: Failed to register memory region 1. Future vtophys translation might fail.
Jun 26 14:06:52 localhost spdk[25901]: VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
Jun 26 14:06:52 localhost spdk[25901]: VHOST_CONFIG: vring call idx:1 file:36
Jun 26 14:06:52 localhost spdk[25901]: rte_vhost_compat.c:  81:vhost_session_mem_register: *WARNING*: Failed to register memory region 0. Future vtophys translation might fail.
Jun 26 14:06:52 localhost spdk[25901]: rte_vhost_compat.c:  81:vhost_session_mem_register: *WARNING*: Failed to register memory region 1. Future vtophys translation might fail.
Jun 26 14:06:52 localhost spdk[25901]: nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: READ sqid:2 cid:191 nsid:1 lba:0 len:8 SGL DATA BLOCK ADDRESS 0x0 len:0x0 key:0x0
Jun 26 14:06:52 localhost spdk[25901]: nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:2 cid:191 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
Jun 26 14:06:52 localhost spdk[25901]: bdev_nvme.c:2560:bdev_nvme_readv: *ERROR*: readv failed: rc = -14
Jun 26 14:06:58 localhost spdk[25901]: nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: READ sqid:2 cid:191 nsid:1 lba:1073740800 len:8 SGL DATA BLOCK ADDRESS 0x0 len:0x0 key:0x0
Jun 26 14:06:58 localhost spdk[25901]: nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:2 cid:191 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
Jun 26 14:06:58 localhost spdk[25901]: bdev_nvme.c:2560:bdev_nvme_readv: *ERROR*: readv failed: rc = -14

[root@localhost ~]# cd /var/tmp
[root@localhost tmp]# ll
total 20
-rw------- 1 root root    4 Jun 26 10:35 spdk_cpu_lock_013
-rw------- 1 root root    4 Jun 26 14:05 spdk_pci_lock_0000:cc:00.0
-rw------- 1 root root    4 Jun 26 13:55 spdk_pci_lock_0000:cd:00.0
srwxr-xr-x 1 root root    0 Jun 26 14:05 spdk.sock
-rw------- 1 root root    0 Jun 26 10:09 spdk.sock.lock
drwx------ 3 root root 4096 Jun 26 08:27 systemd-private-e74b16ded417405aac1860be61cb82dc-chronyd.service-cwP95M
drwx------ 3 root root 4096 Jun 26 08:27 systemd-private-e74b16ded417405aac1860be61cb82dc-systemd-logind.service-YNNlMw
srwxrwxrwx 1 root root    0 Jun 26 14:06 vhost.0

**Note: Under 24.01spdk, with the same configuration, the block devices inside the virtual machine are good**

**Comment by DanPear** [comment]
Please open an issue with the [Storage Performance Development Kit](https://github.com/spdk/spdk) project.
