### ISSUE TITLE
Does option -Suw disable the caching when enabling it for the temp disk or Ephemeral Os disk?

### ISSUE THREAD

**Issue by abenhassouna** [Microsoft/diskspd#215]
Hello Team,

We are trying to benchmark the Ephemeral OS disk on Azure (or Temp disk) which is directly attached to the local host.
For this test we are using the below command:
**.\diskspd -t1 -o32 -b4k -r4k -w100 -d60 -L -Suw -c1G C:\IO05.dat**

When Suw is enabled that means software and hardware caching are both disabled, for a such scenario for temp or Ephemeral Os disk that uses the local disk (means here using caching) will the option -Suw be taken into consideration or even with that we will be using host caching? 
I have tried to prove this but until now didn't find anyway to confirm that.
Thank you for the clarification!

**Comment by dl2n** [comment]
These options control parameters provided by DISKSPD to the Win32 CreateFile API, nothing further. The interpretation of them as "software" and "hardware" caching are with respect to the OS environment it is running in, as-if it were a physical host.  When running inside a VM, its limited to that VM - whether behavioral options cross the guest/host boundary is a matter of the virtualization layer.

The u/unbuffered flag corresponds to FILE_FLAG_NO_BUFFERING. If the target is a file, this causes the hosting filesystem to skip taking reads/writes through the OS file cache. In your case it is a file, so it has effect.

The w/write-through flag corresponds to FILE_FLAG_WRITE_THROUGH. If u/unbuffered wasn't specified this would cause the filesystem flush writes from the cache before returning to the application. It also provides a hint down to the storage layer that is passed via hardware/protocol specific means to, generally, indicate that writes should not complete into volatile storage, e.g. a non-power-persistent cache of any form. The SCSI Force Unit Access (FUA) flag is one of these mechanisms.

Taking this into the hosting environment, the usual expectation is that any writes from a guest MUST be taken to persistent storage, independent of whether the FUA or equivalent is transferrable/transferred over the guest/host storage layer. But this is a zone for implementations to have some say in behavior, so you should carefully observe what happens.

**Comment by dl2n** [comment]
Closing, assume this was helpful. Please reopen if needed. I edited the text a bit for clarity.
