### ISSUE TITLE
Process-diskspd.ps1 does not export file path of the xml

### ISSUE THREAD

**Issue by mghiya** [Microsoft/diskspd#22]
When running different profiles, we tend to name the xml files with the test they perform. When all of these xml files are put together in a folder, we can easily identify the test that was run by looking at the xml file's name. When the Process-Diskspd.ps1 file compiles the results.tsv file, it does not have any column to distinguish between all the xml results and it is difficult to match results in each row to a certain file. It would be great to have the file path as a column to identify where the results came from.

**Comment by dl2n** [comment]
Check out the latest push. The result filename should appear as ResultFileName. I also simplified the output processing.

**Comment by dl2n** [comment]
I'll close, let me know if this didn't do it.

The way I've generally handled it was to make the individual runs identifiable by parameter sets (i.e., pivot by threads, buffersize, etc.). I agree having the filename in there helps.

**Comment by mghiya** [comment]
Yup, that helps! I am curious about the 3 new columns (Add1, Add2, Add3) added to the start of the list. Those columns seem to just have the values "na".
