### ISSUE TITLE
100% read tests appear to use test files which are all zeros

### ISSUE THREAD

**Issue by vslapp** [Microsoft/diskspd#24]
Is it possible to ensure each time a 100% read test is run is executed that there is non-zero data in the test file?

Even when I use a 100% write test first, which does appear to write out non-zero data to the file, when I run the 100% read test, it zeros it out again.

Thanks.

**Comment by marksantaniello** [comment]
That's exactly what "initialization" does.  You don't need to put a write test in the recipe at all.  You must be testing an HDD (or some device which StorScore doesn't auto-detect as an SSD) which means we don't initialize by default.  But you can always pass --initialize on the command line to opt-in to this behavior.  Here's a code reference:
https://github.com/Microsoft/StorScore/blob/8b0a0162878d1f04f43a036e3c1964c64e6f427c/lib/Target.pm#L290-L294

**Comment by marksantaniello** [comment]
BTW, if you *are* actually testing an SSD, you might just want to override the automatic target detection with --target_type:

https://github.com/Microsoft/StorScore/blob/8b0a0162878d1f04f43a036e3c1964c64e6f427c/lib/Target.pm#L177-L179

**Comment by vslapp** [comment]
is this possible with DiskSpd? It looks like you are referring to StorScore.

**Comment by marksantaniello** [comment]
Ahh yes very sorry.  Don't drink and GitHub, eh?

**Comment by marksantaniello** [comment]
I think for DiskSPD you should be able to execute a read test against a pre-created file.  You can pre-create the file any way you like.  (That's exactly what we do in StorScore, which uses DiskSPD under the hood.)

**Comment by vslapp** [comment]
understood... thanks for the feedback.

**Comment by vslapp** [comment]
Ok just loaded an initialized file (confirmed through file editor that all data was non-zero). Ran the 100% read test and everything was good. Stopped the test and ran it again 10 seconds later, results very different. Looked at the file again, all zeros. Any idea?

**Comment by marksantaniello** [comment]
Can you share the command line?

**Comment by vslapp** [comment]
C:\DiskSpd\amd64fre\diskspd.exe -b8K -c1G -d1800 -t16 -L -o4 -r -Sh -w0 -Z1G f:\iodat.dat

**Comment by marksantaniello** [comment]
The -c1G means you are asking DiskSPD to create a file.  Can you try without it?

**Comment by vslapp** [comment]
Yes that seems to be better.
