### ISSUE TITLE
Not parsing options correctly

### ISSUE THREAD

**Issue by joejustesen** [Microsoft/diskspd#26]
It appears that sometimes the options passed to diskspd are not parsed correctly and treated as files.  Here is an example output:

diskspd –b8K –d30 –o4 –t8 –h –r –w10 –L –Z1G –c20G K:\iotest.dat 
Error opening file: ûd30 [2]  
Error opening file: ût8 [2]  
Error opening file: ûr [2]  
Error opening file: ûL [2]  
Error opening file: ûZ1G [2]  
Error opening file: ûb8K [2]  
Error opening file: ûo4 [2]  
Error opening file: ûh [2]  
Error opening file: ûw10 [2]  
Error opening file: K:\iotest.dat [2]  
Error opening file: ûc20G [2]  
There has been an error during threads execution

**Comment by marksantaniello** [comment]
Looks to me like your command line has a unicode dash character and not a real hyphen.  You probably cut and pasted from a unicode document?  Try typing it in manually.
