### ISSUE TITLE
-Z option with file name does not work

### ISSUE THREAD

**Issue by sanjeevrsharma** [Microsoft/diskspd#28]
According to documentation source of write buffer can be defined by -Z<size>[K|M|G|b],<file> but it does not work.

PS C:\Tools> .\diskspd.exe  -c99G -b64K -F1  -s8b   -w100 -o32 -d300 -Sh  -W10 -**Z64K,file.mp3** Z:\testfile.dat

At line:1 char:74
+ ...   -c99G -b64K -F1  -s8b   -w100 -o32 -d300 -Sh -L -W10 -Z64K,file.mp3 ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument

**Comment by lauracaulfield** [comment]
I use a similar commandline (including -Z) which works.  Perhaps you need "" around file.mp3?

**Comment by sanjeevrsharma** [comment]
-Z64k works but -Z64K,file.mp3 does not work. Maybe the feature is not supported or the syntax is documentation is wrong.

**Comment by lauracaulfield** [comment]
Try running it in a normal command window (not in powershell).  The error message you're getting is from powershell.

**Comment by dl2n** [comment]
Use a back quote to escape the option which uses comma. My phone doesn't let me say it properly, but like this:

'-Z20M,foo.mp3

... but with the back quote, not forward.

Syntactically I'd like to give Diskspd another intra switch separator that doesn't conflict with powershell without being aesthetically a mess. I'll look again ...

Sent from my Windows Phone
________________________________

**Comment by dl2n** [comment]
I'll assume this is closed.
