### ISSUE TITLE
Write test samples in the documentation are 100% read instead of 100% write workload

### ISSUE THREAD

**Issue by Magnificus36** [Microsoft/diskspd#29]
In the documentation document (Word and pdf) in section 7 "Sample command lines" the write test have the flag '-w' instead of '-w100' resulting in a 100% read-only workload (as described in the description of the -w<percentage> parameter).

**Comment by DanPear** [comment]
The documentation has now been migrated to the [Wiki](https://github.com/Microsoft/diskspd/wiki) and the command lines have been updated.
