### ISSUE TITLE
diskspd doesn't have check for 4K-volumes

### ISSUE THREAD

**Issue by Wizard17** [microsoft/diskspd#3]
For your information
diskspd -b512 doesn't check if the tested storage is 4096 PhysicalSectorSize and crashes on trying. Annoying if you create benchmark-scripts that have to differentiate between those as it's not easy doing that from a cmd- or PS-script... Would be nice if it would simply say it can't do what you told it to or something. Output of trying -b512 on a native 4K volume:
t[0] error during read error code: 87)
There has been an error during threads execution
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by dl2n** [comment]
Howdy,

Yes, DISKSPD's failure paths in the worker threads are not graceful, and this falls into that fairly wide category: most/all of per-file/target checking is deferred into the worker thread that will do the touch.

I'll keep this open to track.

In the meantime, this bit of powershell shows how to get the logical/physical sector sizes. The first is a 512 native HDD, the second is an SSD showing 512e mode. Your device should show as 4K for both.

PS C:\Windows\wttbin> get-physicaldisk -SerialNumber Z1X02H4100009329E3H6 | select *SectorSize | fl

LogicalSectorSize  : 512
PhysicalSectorSize : 512

PS C:\Windows\wttbin> 
PS C:\Windows\wttbin> get-physicaldisk -SerialNumber BTHV443503XH400JGN | select *SectorSize | fl

LogicalSectorSize  : 512
PhysicalSectorSize : 4096

**Comment by dl2n** [comment]
Closing old issue. We expect analysts do need to understand the properties of their storage subsystem. This is pretty straightforward for single devices (above) in PS1.

The issue of the (lack of) gracefullness in how DISKSPD errors out when execution fails in a worker thread is still open, but its not a 4KN issue.
