### ISSUE TITLE
Create-Vmfleet.ps1 should check that $basevhd actually exists

### ISSUE THREAD

**Issue by MortenRei** [Microsoft/diskspd#30]
Hi

Create-Vmfleet.ps1 should check if the $basevhd file actually exist, instead of throwing a large amount of errors for every single VM that should have been created. 

Example;

```
If (!(test-path -path $Basevhd)) {
    Throw "basevhd not found."
}
```

**Comment by dl2n** [comment]
This is handled in the recent commit.
