### ISSUE TITLE
check-pause & clear-pause do not reference to anything in Start-sweep.ps1

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [microsoft/diskspd#31]
check-pause & clear-pause do not reference to anything in Start-sweep.ps1.

check-pause : The term 'check-pause' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At C:\ClusterStorage\Collect\control\start-sweep.ps1:322 char:33
+     if (-not ($checkpause -and (check-pause -isactive:$true))) {
+                                 ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (check-pause:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Are these ment to be aliasses?
If I replace the functions with the actual scripts, it works.

**Comment by wangkanai** [comment]
Sorry for asking. Do i need to import the function first?

**Comment by dl2n** [comment]
It needs to be on your path.

I suspect you are running from a different node than you ran Install-VMFleet on. Install-VMFleet does this on the node which installs the script set. If you like, the powershell to do that toward the bottom of that script – it is fairly small. Or you can run on the same node you installed it through.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wangkanai** [comment]
@dl2n Thank you. Found it, the `install-vmfleet` only install the path the host where the script was executed on. for other hosts need to execute the following script.
```
$control = 'C:\ClusterStorage\collect\control'

# put the control directory onto the path
if (-not ([System.Environment]::GetEnvironmentVariable("path") -split ';' |? { $_ -eq $control })) {
    $newpath = [System.Environment]::GetEnvironmentVariable("path") + ";$control"
    [System.Environment]::SetEnvironmentVariable("path",
                                                 $newpath,
                                                 [System.EnvironmentVariableTarget]::Process)
    [System.Environment]::SetEnvironmentVariable("path",
                                                 $newpath,
                                                 [System.EnvironmentVariableTarget]::User)
}
```
VM fleet should add the control path to add all the hosts in the cluster for high availability and portability test.

**Comment by dl2n** [comment]
I have tried remoting that fragment to all cluster nodes and for unknown reasons it doesn’t take effect.

What could work is to install as a module on all nodes; the downside is that it becomes hidden off under $env:windir and, for rapid development, that’s far less convenient. I might give it a shot though.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BarnumD** [comment]
I was not running this from a different node, but from a different user account and ran into this issue.
