### ISSUE TITLE
Active KGroups 2 > 1 and/or processor count 104 > 64.

### ISSUE THREAD

**Issue by xeriax** [Microsoft/diskspd#32]
hi there,
I am not sure if this issue should be reported here or not.
Having a problem running Diskspd.

WARNING: Complete CPU utilization cannot currently be gathered within DISKSPD for this system.
         Use alternate mechanisms to gather this data such as perfmon/logman.
         Active KGroups 2 > 1 and/or processor count 104 > 64.

any ideal to fix this problem?

**Comment by dl2n** [comment]
We suspect that rotating a thread through KGROUPs (via hard affinity) and sampling each, in turn, with the non-KGROUP aware APIs will work. There has not been time to try this out yet though.

**Comment by DanPear** [comment]
This issue has been addressed in 3122af8e8bf6fbe74c7c50c1bf9024016d575533 and confirmed as working.
