### ISSUE TITLE
test-clusterhealth.ps1 cannot run on NanoServers

### ISSUE THREAD

**Issue by jaromirk** [Microsoft/diskspd#33]
It would be great if the test-clusterhealth.ps1 could run against cluster (not on cluster) as NanoServer does not have failover clustering module, therefore it does not run.

**Comment by dl2n** [comment]
Yes, there are a few other details regarding the rest of the VM Fleet infrastructure as well, being able to run outside of the cluster itself.

I would very much welcome contribution. It is likely this will happen in the medium term regardless.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
