### ISSUE TITLE
test-clusterhealth and Mellanox Connect-x 4 cards

### ISSUE THREAD

**Issue by kristopherjturner** [microsoft/diskspd#40]
When running the test-clusterhealth.ps1 script I get errors trying to check RoCE configurations. 

Unknown adapter type: Mellanox ConnectX-4 Lx Ethernet Adapter

**Comment by dl2n** [comment]
Can you try something out?

If look down the script you should be able to identify the switch block which produces the “Unknown adapter type” message.


  *   Change: switch ($using:drvdesc) -> switch -wildcard ($using:$drvdesc)
  *   Change the “Mellanox ConnectX-4 Adapter” case to “Mellanox ConnectX-4*”

See if it works.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by krisjturn** [comment]
Sorry for the late update:

I did the two changes above except for the switch -wildcard ($using:$drvdesc). Didn't like that one but if I did this ($using:drvdesc) it would accept this.

It went farther this time.  ON section RDMA Adapter (Virtual) IP Check  This one fails.
Also under RoCE:  Mellanox Error Check, I am getting disconnect drops, however I don't see those disconnect drops on the servers themselves.

Then anything in the SMB CSV Multichannel Symmetry check section fails on down to the end of the script. 

I have the latest drivers installed for these cards.  At the time it was 1.7....

**Comment by BarnumD** [comment]
Also saw this on our ConnectX-4 cards.

**Comment by JosiahBradley** [comment]
I fixed this by simply copying the other ConnectX-4 block to a new block with our adapters name. They use the same counters so it works fine.

"Mellanox ConnectX-4 Lx Ethernet Adapter" {
                $pc = @{
                    '\Mellanox WinOF-2 Diagnostics(_Total)\Responder out of order sequence received' = 'Out Of Order';
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Received Bad CRC Error' = 'Rec BadCRC';
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Received Frame Length Error' = 'Rec FrmLenErr';
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Received Symbol Error' = 'Rec SymlErr';
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Received Discarded' = 'Rec Discard';
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Outbound Discarded' = 'Outbnd Discard'
                    '\Mellanox WinOF-2 Port Traffic(_Total)\Packets Outbound Errors' = 'Outbnd Err';
                }
            }
