### ISSUE TITLE
failed creation of initial load file for

### ISSUE THREAD

**Issue by devalian** [Microsoft/diskspd#42]
Hi, i follow the normal guide, and i did this before. but now regardless how i did it, it shows the error.

anyone know whats wrong?
![capture](https://user-images.githubusercontent.com/19248674/30490812-b6ef21ec-9a6d-11e7-8ad3-8de702c5a85a.PNG)

**Comment by devalian** [comment]
- created new vm, mount iso and perform new installation, using windows server core, key in local admin password, no sysprep. copied vhdx to collect folder
- destroy everything and rebuild

**Comment by dl2n** [comment]
Create-VMFleet will try to create a 10GiB load file @ C:\run in the VM’s VHDX. This is not currently configurable.

I normally run with 25GiB base VHDXs which are large enough to allow for this.

If you know how much freespace there is in your VHDX, go ahead and modify create-vmfleet (look for the “fsutil file createnew”) as you need. This could certainly be made more user friendly in the future – perhaps check the freespace in the base VHDX prior to fleet creation and warn if the default (or specified) load file space is not available.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by devalian** [comment]
ah! thanks so much! using core and only created 10GB vhdx. thanks so much for the pointer!
