### ISSUE TITLE
Incorrect proc count reported

### ISSUE THREAD

**Issue by mpilecki** [Microsoft/diskspd#43]
Hi,
I am doing some testing on 4 socket/48 cores/96 LP machine and from diskspd results I get:
proc count:		128

Any idea what's wrong here?

Regards,
M.

**Comment by audunj** [comment]
I'm seeing something similar:
Testing on a VM setup with 4 sockets / 1 core per socket
diskspd.exe -d15 -b8K -o2 -r -L -Sh -w50 -t4 -c10G -Z1G -C0 -W5 -Rtext e:\diskspd.dat

Output:
thread count:		4
proc count:		64

??

**Comment by DanPear** [comment]
I believe the application should use ActiveProcessorCount and not MaximumProcessorCount when calculating the number of CPUs. Is it possible for either of you to modify [Common.h](https://github.com/Microsoft/diskspd/blob/ceedfbc9c38b1c0cf92e65d4bd94c5289a69b0fe/Common/Common.h#L379) with the following:

`_ulProcCount += _vProcessorGroupInformation[i]._activeProcessorCount;`

**Comment by DanPear** [comment]
This should be corrected now in the commit 3122af8e8bf6fbe74c7c50c1bf9024016d575533 from tomoot.
