### ISSUE TITLE
diskspd on win2008 server: not allowed win32 application

### ISSUE THREAD

**Issue by vieledinge** [Microsoft/diskspd#44]
DiskSpd.exe 2.0.17a dosn't start on win2008 server (no R2) with "not allowed win32 application

"

**Comment by dl2n** [comment]
Are you referring to the binary release @ http://aka.ms/diskspd?

That is correct. There were issues of CRT/STL in the cross-release build environment we use that meant dropping the Vista/Windows 2008 platforms. There were a couple minor changes made which required support not available in the compatible CRT/STL implementations. Windows 7/2008 R2 is as far back as we can go.

If you can try compiling from source in Visual Studio directly on Vista/Windows 2008 it might be possible (with very minor changes) to produce a version which will work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vieledinge** [comment]
Thanks for the Infos. Is there a Download of older versions available?
