### ISSUE TITLE
Diskspd testing against SSD and Microseconds

### ISSUE THREAD

**Issue by darrensmithcom** [Microsoft/diskspd#45]
Hi, hope this is the correct place for raising this question. When using Diskspd against 4 SSD's (RAID 5 array) we are seeing higher than expected latency figures (see below), which are baffling us. However after some research it appears that some other users are saying when you use Diskspd against SSD's the figures are in Microseconds.   Please can someone confirm this is the case? 
Thks Darren

  %-ile |  Read (ms) | Write (ms) | Total (ms)
----------------------------------------------
    min |        N/A |      4.720 |      4.720
   25th |        N/A |     18.149 |     18.149
   50th |        N/A |     26.806 |     26.806
   75th |        N/A |     47.153 |     47.153
   90th |        N/A |     92.725 |     92.725
   95th |        N/A |    143.233 |    143.233
   99th |        N/A |    318.068 |    318.068
3-nines |        N/A |    864.756 |    864.756
4-nines |        N/A |   1580.786 |   1580.786
5-nines |        N/A |   2070.190 |   2070.190
6-nines |        N/A |   2418.533 |   2418.533
7-nines |        N/A |   2653.430 |   2653.430
8-nines |        N/A |   2653.430 |   2653.430
9-nines |        N/A |   2653.430 |   2653.430
    max |        N/A |   2653.430 |   2653.430

**Comment by dl2n** [comment]
The reporting is in milliseconds in all cases. The column headers are accurate. They would be “us” or similar if they were in microseconds.

Depending on the specific workload you are simulating and the adapter capability, RAID5 can have a very large IO multiplier associated with it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
