### ISSUE TITLE
DISKSPD does not validate the XML input schema - hard to debug

### ISSUE THREAD

**Issue by dl2n** [Microsoft/diskspd#5]
DISKSPD does not use schema validation on the input schema (-X<spec>). This makes it difficult to debug typos and is a barrier to adoption of the run spec format. Use the xsd for validation so that reasonable errors can be provided to the user.

**Comment by dl2n** [comment]
This is in progress in 2.0.16b. Need to complete the jujitsu of having loaded the xds to the schema collection -> application.

**Comment by DanPear** [comment]
Check the commit 95b6723f3aadae27accdbb1445e94756cf9677f3 for a possible solution.
