### ISSUE TITLE
Use of Diskspd for stress testing 

### ISSUE THREAD

**Issue by v-sankod** [Microsoft/diskspd#56]
Hi all, 

I am not sure if this is the right platform for me to address my requirement. 
I am looking for just stressing out the HDD/SSD  by doing 100% write to the disk and checking some basic info as to how the disk is enduring during stress. 
I am are not looking for performance measurement here. Just want to run diskspd for ~30 minutes and check if the disk is behaving well during stress. 

Please let me know what test I should perform and what result I should be looking for ? 
Kindly help me :)

I tried writing to the disk (100% write for 10 mins ) using the following command  
diskspd.exe -b256K -t1 -w100 -W5 -o64 -Swu -r -d600 -Z20M -L,0_pct_comp.bin #2

And got the output like so : 
Total IO
thread |       bytes     |     I/Os     |     MB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |    121647398912 |       464048 |     193.35 |     773.40 |   82.740 |    41.172 | #2 (894GB)
-----------------------------------------------------------------------------------------------------
total:      121647398912 |       464048 |     193.35 |     773.40 |   82.740 |    41.172

Read IO
thread |       bytes     |     I/Os     |     MB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |               0 |            0 |       0.00 |       0.00 |    0.000 |       N/A | #2 (894GB)
-----------------------------------------------------------------------------------------------------
total:                 0 |            0 |       0.00 |       0.00 |    0.000 |       N/A

Write IO
thread |       bytes     |     I/Os     |     MB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |    121647398912 |       464048 |     193.35 |     773.40 |   82.740 |    41.172 | #2 (894GB)
-----------------------------------------------------------------------------------------------------
total:      121647398912 |       464048 |     193.35 |     773.40 |   82.740 |    41.172

  %-ile |  Read (ms) | Write (ms) | Total (ms)
----------------------------------------------
    min |        N/A |     31.242 |     31.242
   25th |        N/A |     33.822 |     33.822
   50th |        N/A |     96.928 |     96.928
   75th |        N/A |    103.014 |    103.014
   90th |        N/A |    153.568 |    153.568
   95th |        N/A |    156.915 |    156.915
   99th |        N/A |    160.514 |    160.514
3-nines |        N/A |    163.477 |    163.477
4-nines |        N/A |    165.460 |    165.460
5-nines |        N/A |    167.004 |    167.004
6-nines |        N/A |    168.096 |    168.096
7-nines |        N/A |    168.096 |    168.096
8-nines |        N/A |    168.096 |    168.096
9-nines |        N/A |    168.096 |    168.096
    max |        N/A |    168.096 |    168.096

**Comment by dl2n** [comment]
“Behaving well” is not a well defined test. All DISKSPD does is what it says it is doing; in this case


  *   256KB IO
  *   1 thread
  *   100% write
  *   5 second warmup
  *   up to 64 IOs outstanding
  *   unbuffered writethrough IO
  *   random IO pattern across the target at IO size alignment (256KB)
  *   run for 600 seconds
  *   20MB random write source buffer (each write buffer will be random chosen from this, at 4 byte random alignment)
  *   Gather latency data
  *   An apparent syntax error which DISKSPD may ignore re: 0_pct_comp.bin (you may have intended this to be put against -Z20M, in which case the write source buffer would have been initialized from that file)
  *   run v. PhysicalDisk2

If this is what you wanted, you have to use the statistics to reason about goodness. I don’t know what you consider good.

In general, 193MB/s indicates the drive is reordering the queued IO into a good elevator sweep across the HDD. The 64QD attempt is responsible for that, at a cost of about 84ms per IO and a large standard deviation of 42ms. The latency is actually lower than I would have expected all things considered. The latency percentiles seem pretty much in control given the worst case is only 170ms or so.

The real question to ask is whether this is the right way to characterize the device for the workload you want to apply to it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dl2n** [comment]
You are probably not administrator (5 == ERROR_ACCESS_DENIED).

However, if you run a write test on the raw physical device (#5), it will do so – and irretrievably corrupt whatever is on the device, including the filesystem. This is how chkdsk works :-)

If you want to run through the filesystem, mount it and create a file to run DISKSPD against.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by v-sankod** [comment]
Thanks for your quick response.
I had ran diskspd in admin mode. 
These are the steps I followed: 

diskpart> select disk 1
diskpart> create partition primary
diskpart> format fs=ntfs quick

Ran DiskSpd.exe -b256K -t1 -w100 -W15 -o64 -Swu -r -d10 -Z20M,0_pct_comp.bin #1
error during overlapped IO operation (error code: 5)
There has been an error during threads execution

Command Line: DiskSpd.exe -b256K -t1 -w100 -W15 -o64 -Swu -r -d10 -Z20M,0_pct_comp.bin #1

Input parameters:

        timespan:   1
        -------------
        duration: 10s
        warm up time: 15s
        cool down time: 0s
        random seed: 0
        path: '#1'
                think time: 0ms
                burst size: 0
                software cache disabled
                hardware write cache disabled, writethrough on
                write buffer size: 20971520
                write buffer source: '0_pct_comp.bin'
                performing write test
                block size: 262144
                using random I/O (alignment: 262144)
                number of outstanding I/O operations: 64
                thread stride size: 0
                threads per file: 1
                using I/O Completion Ports
                IO priority: normal



Results for timespan 1:
*******************************************************************************
The test was interrupted before the measurements began. No results are displayed.
Error generating I/O requests

**Comment by dl2n** [comment]
What was the error that time?

**Comment by dl2n** [comment]
No response, closing.
