### ISSUE TITLE
Translating diskspd to linux FIO

### ISSUE THREAD

**Issue by JonKohler** [Microsoft/diskspd#57]
I'm working on a project that uses a distributed storage benchmarking harness that leverages linux FIO under the covers to run storage level workloads on a set of systems.

The general overview is that you can feed specifications into the harness, and it will run them against various infrastructure targets, taking systematic care to minimize the number of variables, such that the runs are comparable between each other.

The idea here is that you'd use this harness to compare different types of infrastructure in a very standardized way. One way might be running against the same infrastructure, but different hardware/firmware configurations. Another way might be different types of storage (e.g. quantifying putting in Intel Optane vs standard NVMe devices, etc). Another way might be same hardware/storage, but different hypervisors or different device drivers.

There are a few Microsoft based applications that we've previously modeled in diskspd with a great degree of accuracy, that we'd love to port into this harness, such that we have one engine to rule them all, without having to add windows support to the harness and maintain two different workload generators.

To that end, has anyone approached this from a "translation" perspective before? Such as diskspd call/option XYZ == FIO parameter ABC, such that running either XYZ or ABC produces the same storage IO pattern/demand?

**Comment by dl2n** [comment]
In theory it should be quite feasible to translate diskspd cmdline options to FIO and vice versa. I think both generally have main modes of operation that spin threads, open IO targets (files, volume, raw media) and issue either rate limited or targeted queue depths of IO per thread and results from there. Both definitely have modes of operation specific to their original operating environment (POSIX, Windows) and those won’t translate.

Devil is in the details. No, I haven’t seen a take on this. If you want to take a shot I’d be happy to answer q’s.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
