### ISSUE TITLE
feature request: output diskspd run start and end date time in UTC

### ISSUE THREAD

**Issue by fliang-ms** [Microsoft/diskspd#65]
The script calling diskspd.exe can definitely add the similar information. But it cannot get the accurate timestamp when warm ends, real run starts and stops. Those timestamps are super useful while reviewing disk IOs issued by diskspd in other tools, like perfmon, WPA, etc.

**Comment by fliang-ms** [comment]
thank you for sharing. I didn't know that xml output has timestamp. I usually capture an ETL file while running diskspd. Then I look into the disk IO summary table in WPA to understand disk IO patterns. Finding timestamp from xml output definitely solves my problem. But it is much easier for people to quickly finding out information in txt output. Just my 2 cents.

**Comment by dl2n** [comment]
Fair enough comment (I wonder who made it … :-)), I'll leave this up as a reminder that might not be a bad idea. In general, though, we're free and far more verbose/complete in the XML than we could possibly be in the TXT without making it a lot larger. XML we have to be since it turns into an artifact in a lot of usages (which system did I run that on? all the pivots of thread/file result aggregation, etc.).

**Comment by DanPear** [comment]
You raise an interesting point about analysis. It's fairly common that an ETL is captured when diskspd is run. There's a comment in [IORequestGenerator](https://github.com/Microsoft/diskspd/blob/a796c20fda87a793b2032d31d253ded1fff29dbb/IORequestGenerator/IORequestGenerator.cpp#L2279) regarding inserting an ETW mark as a future extension.

It's probably a good idea for completeness to display a limited amount of system information from within ResultParser but I think it'd be even more useful if we had diskspd spit out ETW events throughout its various phases.

**Comment by DanPear** [comment]
We'll split this in two to track both items. We'll use issue #66 to update the ResultParser to display the start time in UTC as well as some additional system information and issue #67 to support Event Tracing for Windows events.

**Comment by fliang-ms** [comment]
thank you very  much.

**Comment by DanPear** [comment]
Closing this off as both issues have been addressed in the 2.0.21a release.
