### ISSUE TITLE
VMFleet test on production system

### ISSUE THREAD

**Issue by itn18** [Microsoft/diskspd#68]
Hello,
Can I test a S2D production system using vmfleet, where virtual disks (CSV) and VMs are currently in production?  Looking to load VMFleet, test and then clear all VM's created by VMFleet manually after.
Will installing VMFleet modify any existing virtual disks or VMs?
Thx

**Comment by dl2n** [comment]
VM Fleet assumes volumes dedicated for its use, following a <nodename> prefix convention (see the documentation). Generally, that would be one (or more) per node.

It will not modify any existing VMs, and it will not use volumes which do not match that pattern.

In general it is only used in benchmarking or pre-production testing of hardware, so this question hasn't come up.
