### ISSUE TITLE
Configure Simultaneous Different Workloads on Diskspd & VMFleet

### ISSUE THREAD

**Issue by itgl72** [Microsoft/diskspd#69]
I've been working with Diskspd and VMfleet for a while now trying different workloads in environments with reasonable success but I've not been able to configure a stress test with Diskspd to use the -X parameter. Has anyone had success setting up the XML file for configuring workloads of different types to run simultaneously on a group of VMs in the cluster? I could use a configuration example if anyone has one that they've got to work.

**Comment by lauracaulfield** [comment]
I don't have a file handy just now, but here's a trick I've used successfully in the past.  Run DiskSpd using the non-xml command line parameters, and set the output to xml (-R).  Then, grab the "profile" section of the output and use that as the xml input file.  Also, I believe there's no space between -X and the name of the profile's file.

**Comment by itgl72** [comment]
Thanks for the feedback, its a start for me to start pointing in the right direction.
