### ISSUE TITLE
Document what the score means

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [Microsoft/diskspd#70]
I have not been able to find any information on this. The problem I have with it is that it seems inconsistent with the rest of the output, yet the results of the famous CrystalDiskMark are based on it.

Example:
```
Total IO
thread |       bytes     |     I/Os     |     MB/s   |  I/O per s |  file
------------------------------------------------------------------------------
     0 |      2775056384 |        21172 |     529.36 |    4234.88 | cdm (1024MB)

------------------------------------------------------------------------------
total:        2775056384 |        21172 |     529.36 |    4234.88

Score: 5550740
```

It's as if the value in the column MB/s is actually MiB/s and the returned score is in MB/s... (And if that truly is the case, then it seems that the heading for the column should be corrected?)

**Comment by DanPear** [comment]
It appears as if you're using an outdated version of the tool. This change was made in the commit cc454914210b568fcbad9a1587a0a77c083a1387. The latest update to Diskspd can be downloaded from <https://aka.ms/diskspd>.

I would also expect that any tools that use Diskspd would specify the -Rxml option and consume the results in XML format. The XmlResultParser would then display the value in bytes. The conventions used are documented under [Size conventions for DiskSpd parameters](https://github.com/Microsoft/diskspd/wiki/Command-line-and-parameters#size-conventions-for-diskspd-parameters).

**Comment by s-h-a-d-o-w** [comment]
My apologies - the above is based on CrystalDiskMark 6.0.1 (which also uses the fact that you used to output the score as exit code). I didn't realize that this has already been addressed...

**Comment by DanPear** [comment]
No worries! Please let us know if you find any issues in the future or if you have any suggestions for improvements.
