### ISSUE TITLE
Test diskspd without specifying a test file size

### ISSUE THREAD

**Issue by codedjw** [Microsoft/diskspd#75]
Hi,
I use the following command-line parameters to run diskspd write test. And I found diskspd will generated a 2TB file at first. 
C:\Diskspd-v2.0.17\amd64fre\diskspd.exe -b4096K -d600 -Suw -L -o2 -t16 -si -w100 -c2046G $file
So by my understanding, the following diskspd test just override some parts of the test file, right?

But our scenario is a append-only operation. So I do not want to limit the file size, I tried to remove the -c2046G option, but fails with the following error:

```
Input parameters:

	timespan:   1
	-------------
	duration: 600s
	warm up time: 5s
	cool down time: 0s
	measuring latency
	random seed: 0
	path: 'XXXX\io.dat'
		think time: 0ms
		burst size: 0
		software cache disabled
		hardware write cache disabled, writethrough on
		performing write test
		block size: 4194304
		using interlocked sequential I/O (stride: 4194304)
		number of outstanding I/O operations: 2
		thread stride size: 0
		threads per file: 16
		using I/O Completion Ports
		IO priority: normal



Results for timespan 1:
*******************************************************************************
The test was interrupted before the measurements began. No results are displayed.

```

Any ways could I do to use diskspd to simulate a append-only write operation?

Thanks.

**Comment by srkusam** [comment]
Hi.. Any resolution identified for this issue..?
