### ISSUE TITLE
Unable to memory map

### ISSUE THREAD

**Issue by rodrigobell** [Microsoft/diskspd#76]
I'm getting the following error when using the new -Sm flag to do memory mapped IO:
```
C:\Rodrigo>diskspd -c2G -d60 -Sm testfile.dat
FATAL ERROR: Could not map view for target 'testfile.dat'. Error code: 0x8
ERROR: Could not map view for target 'testfile.dat'. Error code: 0x8
```
Am I missing something here?

**Comment by DanPear** [comment]
The MapViewOfFile function is failing with 'Not enough memory resources are available to process this command'. You'll either need to reduce the size of the target mapping to less than 2 GB or use a different architecture. You will see the same problem if you try to run the 32-bit version of Diskspd on a 64-bit system.

**Comment by rodrigobell** [comment]
Makes sense, working now. Thanks @DanPear!
