### ISSUE TITLE
Why -Sh?

### ISSUE THREAD

**Issue by limulidae** [Microsoft/diskspd#79]
According to:
https://stackoverflow.com/questions/51315745/createfile-with-file-flag-no-buffering-but-not-file-flag-write-through?rq=1
Does FILE_FLAG_NO_BUFFERING automatically imply FILE_FLAG_WRITE_THROUGH ? – tcb Jul 12 at 23:36
•	yes, this is correct – RbMm Jul 12 at 23:37

It seems to me that -Su is equivalent to -Sh.
Why do we need -Sh?
What's the difference?

**Comment by dl2n** [comment]
The stackoverflow comment is wrong.

NO_BUFFERING refers to not using the filesystem's file cache. WRITE_THROUGH refers to triggering the assertion of SL_WRITE_THROUGH on the down-call from the filesystem to the device storage stack(s), which in turn would assert stack-specific behavior such as FORCE UNIT ACCESS on SAS/SCSI devices.

You can see this here in the FASTFAT sample code we've released.

https://github.com/Microsoft/Windows-driver-samples/blob/65196cb16bfcf7b3ebc6cc52032fd7a0bb7d6691/filesys/fastfat/deviosup.c#L1818

**Comment by dl2n** [comment]
(in case its not clear: behavior like FUA is an instruction to the device to write the data through to persistent storage, and not leave it in volatile device cache)
