### ISSUE TITLE
overlappedQuque is not dequeued completely in doWorkUsingIOCompletionPorts()

### ISSUE THREAD

**Issue by limulidae** [microsoft/diskspd#80]
//for (size_t i = 0; i < overlappedQueue.GetCount(); i++)
        while (overlappedQueue.GetCount())

only half of the queue is removed by the for loop.

**Comment by dl2n** [comment]
Not sure what this was referring to originally, but the IO completion port loop has been rewritten for 2.2 and we do not believe it has dispatch issues. Please take a look and open a new issue if you believe there is something still wrong.
