### ISSUE TITLE
Issue with using it to benchmark an ERAM RAMDisk

### ISSUE THREAD

**Issue by Zero3K** [Microsoft/diskspd#82]
When I try to do it, I get the following error:

ERROR: Could not obtain dynamic volume extents (error code: 1)
The file is too small or there has been an error during getting file size
There has been an error during threads execution

The source code and drivers for it can be found at https://github.com/Zero3K/ERAM.

**Comment by dl2n** [comment]
It should be straightforward to see where this error comes from in DISKSPD (see IoRequestGenerator.cpp).

Have you looked at what is happening in your driver when IOCTL_DISK_GET_PARTITION_INFO_EX & failing over, IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS is issued?

If you haven’t created a partition and are running v. a drive letter (it looks like this is the case), try running against the drive number instead. This will go down a different path if you look further up into where DISKSPD is trying to figure out how big the target is:

//check if it is a disk
            if (fPhysical)
            {
                fsize = GetPhysicalDriveSize(hFile);
            }
            // check if it is a partition
            else if (fPartition)
            {
                fsize = GetPartitionSize(hFile);
            }
            // it has to be a regular file
            else
            { … }

It may be that there is a problem with your driver with respect to lower level fallbacks for unpartitioned (RAW) media that those IOCTLs rely on normally, but it could be that drive letter-mapped raw media simply doesn’t work at the moment. Its not a usual case for us. I’m not sure what those problems could be without further investigation.

See if #<drivenumber> unblocks you first.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Zero3K** [comment]
I made a new version of it recently. You can get it at https://github.com/Zero3K/ERAM/releases/tag/v2.24.

**Comment by dl2n** [comment]
I'm citing from the current source on GitHub. If you're using a version of pre-compiled DISKSPD earlier than 2.0.21a (https://aka.ms/diskspd), it is possible something was fixed along the way. Update in any case, or compile from the head of the master branch here.
