### ISSUE TITLE
Error code: 112 , Not Permissions Issue. 

### ISSUE THREAD

**Issue by RandyDotCom** [Microsoft/diskspd#85]
Command:
..\diskspd.exe -b8k -d30 -o4 -t4 -h -r -w25 -Z1g -L -c10G T:\iotest.dat > Results.txt 
Returns
Error setting end of file (error code: 112)
Error generating I/O requests

What might be the cause?

**Comment by dl2n** [comment]
Not going to disagree that at minimum it would be nice-if DISKSPD provided the error code strings in a common error handling routine.

In this case:

https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-

ERROR_DISK_FULL

Make sure you actually have 10GiB of freespace on the T: drive.

You should also reconsider whether your test will need a 1GiB random write source buffer – that’s quite large. The source buffers are chosen on 512B aligned boundaries within it. A 50MiB buffer would provide 50MiB/512 = ~102,000 different, which is likely more than enough depending on the strength of an inline, realtime deduplicator.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by RandyDotCom** [comment]
Actually, Just adding the link to the readme would be 90%.
