### ISSUE TITLE
Question: Is it possible to get real-time output for BW and IOPs?

### ISSUE THREAD

**Issue by jawalking** [Microsoft/diskspd#87]
I'm looking for a way to get performance curves as SSD drives enters into a steady-state from "fresh out of the box".

Having the ability to pipe IOPs and/or BW to a file per interval specified using -D is what I was hoping to find.

Any help or tips are greatly appreciated.

**Comment by dl2n** [comment]
This is easy to do in a general way with the system performance counters. The XML reporting  (-Rxml) gives you time series IOPS at all the aggregates already, though. If you need examples of getting either please let us know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
