### ISSUE TITLE
2 node windows 2016 cluster - create-vmfleet.ps1 exits without printing /running anything in few secods 

### ISSUE THREAD

**Issue by udhayagen** [microsoft/diskspd#89]
Hi Dan,

This is in continuation of whatever discussion we had from  issue #88. Creating this as new thread / issue with relevant title so that people can refer this whenever / whoever run into similar issues.

As suggested, i've made required changes and re-ran the script but it is not running anything and comes out in few seconds as shown below.

Am i missing any specific steps ? Also, could you please point me to the official link where i can cross-verify the procedure once ?

PS C:\ClusterStorage\Collect\control> dir "C:\ClusterStorage\"

    Directory: C:\ClusterStorage

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l        3/11/2019   9:43 PM                bdldc-r100-srv4-old
d----l        3/12/2019   3:23 AM                bdldc-r100-srv4-vmfleet
d----l        3/11/2019   9:43 PM                bdldc-r100-srv5-vmfleet
d----l        3/11/2019   9:32 PM                Collect

PS C:\ClusterStorage\Collect\control>

PS C:\ClusterStorage\Collect\control> .\create-vmfleet.ps1 -basevhd "C:\ClusterStorage\Collect\GoldVMFleet.vhdx" -vms 2
-AdminPass M!gration12 -ConnectUser "windc\administrator" -ConnectPass Bdarklab123
PS C:\ClusterStorage\Collect\control> .\create-vmfleet.ps1 -basevhd "C:\ClusterStorage\Collect\GoldVMFleet.vhdx" -vms 2
-AdminPass M!gration12 -ConnectUser "windc\administrator" -ConnectPass Bdarklab123
PS C:\ClusterStorage\Collect\control> .\create-vmfleet.ps1 -basevhd "C:\ClusterStorage\Collect\GoldVMFleet.vhdx" -vms 2
-AdminPass M!gration12 -ConnectUser "windc\administrator" -ConnectPass Bdarklab123

**Comment by dl2n** [comment]
Can you show this?

Get-VirtualDisk
