### ISSUE TITLE
diskspd Error Code (58) (1236) (64) error during overlapped IO operation

### ISSUE THREAD

**Issue by suttorpa** [Microsoft/diskspd#92]
Hello,

I am just starting out using diskspd, 2 file servers in my organization are getting complains of slow access to a database that run on those devices

 1 server is generating errors when I do so:

diskspd -b8K -d30 -o4 -t8 -h -r -w25 -L -Z1G -c100M \\myservername_dontbenosy\tempfile.dat > Results.rxml
WARNING: Error adjusting token privileges for SeManageVolumePrivilege (error code: 1300)
WARNING: Could not set privileges for setting valid file size; will use a slower method of preparing the file
error during overlapped IO operation (error code: 58)
error during overlapped IO operation (error code: 64)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 64)
error during overlapped IO operation (error code: 64)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
There has been an error during threads execution
Error generating I/O requests

what the heck are all of these?! the diskspd worked on all other servers..  I couldn't find a manual with the error codes listed.. 

the other server had 400ms latency times (its just overloaded).. t

I sent this information to my server team but is there anything else I can do to resolve this?  To me it looks like disk issues.. but the shares on the drive appear to be working.. if a bit slow..

Thank you for being here!

**Comment by DanPear** [comment]
Please try running the command again from an elevated command prompt.

**Comment by suttorpa** [comment]
Thanks, I tried elevated.. Although I am a power user on my machine, I am not a server administrator of the organization although I do have some elevated rights.. I was able to run the diskspd command on 10 other servers, only this particular server gives me errors.. 

WARNING: Could not set valid file size (error code: 1314); trying a slower method of filling the file (this does not affect performance, just makes the test preparation longer)
error during overlapped IO operation (error code: 58)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
error during overlapped IO operation (error code: 1236)
There has been an error during threads execution
Error generating I/O requests

**Comment by DanPear** [comment]
The initial error is because you don't hold the SE_MANAGE_VOLUME_NAME privilege on that system.

**Comment by suttorpa** [comment]
error 58 = no privilege to access se_manage_volume_name ?

I know all servers gave the "Could not set valid file size (error code: 1314); trying a slower method of filling the file (this does not affect performance, just makes the test preparation longer)" but they still ran..

**Comment by DanPear** [comment]
You'd need to verify the remote share you're trying to write to. Right now the syntax you're using isn't correct as it should be \\\\computername\share\file.name.

For most Windows errors codes you can use the net helpmsg command to determine the error message:
C:\>net helpmsg 1314
A required privilege is not held by the client.

C:\>net helpmsg 58
The specified server cannot perform the requested operation.

C:\>net helpmsg 1236
The network connection was aborted by the local system.
