### ISSUE TITLE
ERROR: "." may not contain DISKSPD result files

### ISSUE THREAD

**Issue by s3banerjee** [Microsoft/diskspd#93]
How to overcome this issue

**Comment by DanPear** [comment]
Is it possible to show the command line you used to see this error?

**Comment by s3banerjee** [comment]
Thanks , attaching

**Comment by s3banerjee** [comment]
attached 
![Powershell](https://user-images.githubusercontent.com/25532907/55815184-ed6a5b80-5abd-11e9-8589-28f24cdd7131.PNG)

**Comment by dl2n** [comment]
Is it?

**Comment by s3banerjee** [comment]
Is anything i'm missing

**Comment by dl2n** [comment]
Is out.xml a DISKSPD XML result? Attach it?

**Comment by s3banerjee** [comment]
out.xml is blank and DISKSPD is not created

**Comment by s3banerjee** [comment]
Seems to be me , missing some steps, what i did is 
a. Download the zip from Github 
b. With some changes ((debugging purpose) in the Process-DiskSpd.ps1 , run that file 
c. getting the error

**Comment by dl2n** [comment]
Yes.

There are two error lines. If you’re familiar with Powershell to the point of making changes to the script, it should be fairly easy to spot where those errors are coming from and understand why.

I assume you also tried to run DISKSPD to produce out.xml. If its empty, that didn’t work and that is exactly what the script is erroring about.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DanPear** [comment]
You'll need to use something like the command below to create the XML results file. You should also make sure there's no other XML files in the directory when you run Process-DiskSpd.ps1.

`.\diskspd.exe -c1M -L -Rxml diskspd.dat > results.xml`
`.\Process-DiskSpd.ps1`

**Comment by s3banerjee** [comment]
Thanks for above steps 

step 1 
.\diskspd.exe -c1M -L -Rxml diskspd.dat > results.xml
step 2
.\Process-DiskSpd.ps1

Unable to find the diskspd.exe after downloading the solution from github

**Comment by s3banerjee** [comment]
so it is failing in step1

**Comment by DanPear** [comment]
The latest update to DiskSpd can be downloaded from https://aka.ms/diskspd.

**Comment by s3banerjee** [comment]
Thanks it worked, few more clarification 
.\diskspd.exe -c1M -L -Rxml diskspd.dat , if I've to check certain other drives along with C:\ , D: \ and other network drive like Q: etc at same time, 
anything specific we can use

**Comment by DanPear** [comment]
You can specify the drive letter as part of the target name: C:\diskspd.dat, D:\diskspd.dat, etc. Please check the documentation at https://github.com/Microsoft/diskspd/wiki for further options.
