### ISSUE TITLE
DiskSpd - cannot target disk by number or drive letter

### ISSUE THREAD

**Issue by Budrumi** [microsoft/diskspd#97]
DiskSpd - cannot target disk by number or drive letter

DiskSpd's help says:
Usage: diskspd.exe [options] target1 [ target2 [ target3 ...] ]
version 2.0.21a (2018/9/21)

Available targets:
       file_path
       #<physical drive number>
       <partition_drive_letter>:

However I haven't found any mention of the option to target disk number or volume letter in the Wiki and anytime I try to use either of those, I get errors:
C:\Users\admin\Desktop\DiskSpd\amd64>diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v #1
Generating requests for timespan 1.
creating thread 0
thread 0 is relative thread 0 for #0
starting warm up...
affinitizing thread 0 to Group 0 / CPU 0
thread 0 starting: file '#1' relative thread 0 file offset: 0 (starting in block: 0)
thread 0 started (random seed: 0)
thread 0: waiting for a signal to start
thread 0: received signal to start
t[0] error during write error code: 5)
starting measurements...
starting cool down...
finished test...
There has been an error during threads execution

Command Line: diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v #1

Input parameters:

        using verbose mode
        timespan:   1
        -------------
        duration: 30s
        warm up time: 5s
        cool down time: 0s
        measuring latency
        random seed: 0
        path: '#1'
                think time: 0ms
                burst size: 0
                using software cache
                using hardware write cache, writethrough off
                performing write test
                block size: 131072
                using sequential I/O (stride: 131072)
                number of outstanding I/O operations: 1
                thread stride size: 0
                threads per file: 1
                IO priority: normal

System information:

        computer name: <redacted>
        start time: 2019/04/29 14:52:59 UTC

Results for timespan 1:
*******************************************************************************
The test was interrupted before the measurements began. No results are displayed.
Error generating I/O requests

I get the same error when targetting the drive (partition) by a letter.

Has this been deprecated or is my syntax incorrect?

**Comment by dl2n** [comment]
Error 5 is ERROR_ACCESS_DENIED. In order to access drives, you must be running elevated or as administrator.

Be very careful doing write tests (-w100) to drives. Any content on the drive will be wiped out – partitioning, formatted volumes, any other content.

Agreed it would be helpful if DISKSPD used standard error code formatting to display the underlying error message.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18362 - 16.0.11601.20126]

________________________________

**Comment by Budrumi** [comment]
Dan, thanks for replying. Ofcourse I made sure I'm running the commands from the elevated prompt.
I'm also aware it will wipe all data.

**Comment by DanPear** [comment]
Can you verify if the disk contains at least one formatted partition? If not, please try creating a partition, formatting it and then running the test again.

**Comment by Budrumi** [comment]
Yes, it's the same disk/partition I used for testing using a test file.
I just did more quick testing - I've created 5GB dynamic VHDX on my PC, formatted as NTFS4k, here's Get-Volume ouput confirming the volume is there:

> PS C:\> Get-Volume -DriveLetter D
DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining    Size
>D           New Volume   NTFS           Fixed     Healthy      OK                      4.96 GB 4.98 GB`
>PS C:\> get-disk -Number 1
Number Friendly Name                                                                      Serial Number                    HealthStatus         OperationalStatus      Total Size Partition                                                                                                                                                                             Style
1      Msft Virtual Disk                                                                                                  Healthy              Online                       5 GB GPT

Tried running the tests (elevated prompt/PSH):
1) diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v D:
This gives me the error I described above
2) diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v D
which gives slightly different error: "Error opening file: D [2]"
3) diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v #1
this again gives the original error
4) diskspd.exe -t1 -b128k -d30 -L -o1 -w100 -v -c1G d:\test.dat
This works fine as expected

Sorry for the text formatting, I can't get the quote/code elements to work properly.

**Comment by dl2n** [comment]
Try -w0

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18362 - 16.0.11629.20016]

________________________________

**Comment by Budrumi** [comment]
Read test (-w0) works using both disk number and volume letter.

**Comment by dl2n** [comment]
What I think you're running into is a block in the filesystems that is intended to prevent you from doing a destructive whole-volume operation. Logically, doing a write "test" against a formatted volume is simulating a particularly intense chkdsk/fsck/equivalent; if you aren't chkdsk/fsck, its a mistargeted type of operation.

If you want to run a write test against the raw disk stack, do a Clear-Disk of it to tear down the FS/partitioning and then go at it. If you want to do it through the filesystem, run it against a file (or files) in it.

**Comment by Budrumi** [comment]
Dan, what you're saying makes sense, I did a test on a raw disk (deleted partitions) and write test worked using disk number. Obviously I cannot test that using a drive letter anymore.

So, I'm unsure what to think of these 2 options - testing using disk number works when the disk is raw/unitialized, but documentation doesn't state this requirement.
Testing using drive letter doesn't work when the disk is partitioned/formatted and cannot be used when the disk doesn't contain formatted partitions/volumes, so it makes no sense to me.

Or am I hitting some non-standard behavior (although on reproducible on multiple systems)?

**Comment by dl2n** [comment]
You’re hitting standard behavior. I suppose we’re assuming familiarity with these platform constraints – they are platform constraints, DISKSPD is simply allowing you a path to encounter them.

Doing drive letter-based IO vs. a raw partition should work. Try again if you think that was happening. Internally, there is a trivial RAW filesystem (literally rawfs, though its part of the kernel) which is the default mount, and it allows write. This is in fact the path through which format happens in the system.

However, it gets back to what you’re trying to do. Don’t look at these as constraints – the fact they aren’t allowed in the platform (for solid reasons) is also telling you this isn’t the path through which this type of IO is issued. Even if you could force through them, it wouldn’t be representative of normal operation.

What are you trying to do?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18362 - 16.0.11629.20164]

________________________________

**Comment by Budrumi** [comment]
I guess I'm not understanding something here.
I just wanted to use diskspd as a tool to benchmark certain system. I looked at the current docs, saw 3 ways of targetting drives (file, drive letter, drive number), no mention of constraints/limitations, wanted to compare drive letter and drive number targetting against file-targetting to see if there's any performance difference. Mostly for completeness-sake.
That's all. I'm not trying to go around system limitations or anything like that.

**Comment by dl2n** [comment]
I've updated the Wiki with a better discussion of the target types. Hopefully this would have helped.

[wiki link](https://github.com/microsoft/diskspd/wiki/Command-line-and-parameters)

**Comment by anewhope1** [comment]
Hi there, 

i have the same problem. Even with -w0

- Win Server 2016
- PowerShell

`PS > Get-WmiObject Win32_DiskDrive`

Partitions : 0
DeviceID   : \\.\PHYSICALDRIVE1
Model      : IFT GS 3000 Series  Multi-Path Disk Device
Size       : 536864025600

`PS > Clear-Disk -Number 1 -RemoveData -RemoveOE`

`PS C:\ .\diskspd.exe -d1 -w0 -t4 -o32 -b4k #1`
.\diskspd.exe : ERROR: need to provide at least one filename
In Zeile:1 Zeichen:1
+ .\diskspd.exe -d1 -w0 -t4 -o32 -b4k #1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: need to ...st one filename:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

I tried it for 2 days and many different parameters, without any success. What am i doing wrong?

Aron

**Comment by dl2n** [comment]
The # is the comment character in Powershell. You need to quote this in order to pass it to DISKSPD. Powershell is treating the remainder of the command line as a comment.

Use this:

              `#1

Note the back-tick.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by anewhope1** [comment]
Wow, thank you Dan!
And thanks for the fast response.

I Deleted Ma Post because when i Execute it via normal command line and Not
powershell ist works Fine. So i will Build Ma powershell Script with
Reference To external command line.

Or i just take your Solution.

Thank you and sorry for the iPhone Typo from a german Keyboard ;)

Aron

Dan Lovinger <notifications@github.com> schrieb am Do. 23. Juli 2020 um
18:28:

**Comment by dl2n** [comment]
Yes; at the command shell prompt (cmd.exe) it doesn’t require any special handling - # is not a reserved character for cmd. This is only a matter of using it from powershell, either at the prompt or in script.

We could allow another character to also specify using the raw device – say, @ for @1, @2, etc. – that wouldn’t be special in any of the expected shells, though of course another could come along 😊. It is certainly not ideal to have an option which must be quoted through but that will work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
